- MAiD - Case Management App/force-app/main/default/objects/Case/fields/PHN_No__c.field-meta.xml
- MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Validates_PHN_is_10_digits_if_it_is_BC.validationRule-meta.xml
Component added - Validation Rule 
If BC is selected, then the PHN must be 10 digits
> Validation rule to check PHN is 10 digits

- MAiD - Case Management App/force-app/main/default/flows/Provincial_and_RX_Flow_for_1633.flow-meta.xml
- MAiD - Case Management App/force-app/main/default/layouts/Form_1633__c-Form 1633 Layout.layout-meta.xml
Flow changes for Provincial safeguard flow.
Changes includes the following:-
Rule 59 - Added exception criteria and changed API names in the flow to match the requested fields.
Rule 60 - Changed the Logic in the flow as per Lara's Feedback after testing the Provincial safeguard flow.
Layout changes for removal of assessment interpreter ID from the Form1633 Layout.
> changes for 59 and 60 for provincial safeguard

- MAiD - Case Management App/force-app/main/default/flows/display_warning_for_duplicate_phn.flow-meta.xml
Defect Changes for new PHN Flow
A. Notifications can be generated only for the type :
Discontinuation of Planning: Ineligible
Discontinuation of Planning: Withdrawn Request
B. Status : Closed
> Defect changes for duplicate PHN Notification Flow

- MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
update admin permission  set to update viewAllData to false in order not to have permission to ActiveScratchOrg
ScratchOrgInfo; NamespaceRegistry as required
> update admin permission for viewAllData (False)

- MAiD - Case Management App/force-app/main/default/objects/Case/fields/Historical_Case_Reviewer__c.field-meta.xml
- MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
- MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
- MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Adding Historical Case Owner Field
Files effected:
1. MAiD Analyst Permission Sets - Read Only
2. MAiD Manager Permission Sets - Read Only
3. MAiD System Admin Permission Sets- Edit
4. New Field Addition as - Historical Case Owner from the backend
> Adding Historical Case Owner Field

- MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
New  criteria field "Potential_BCCS_Review" made mandatory in the element Rule 27 in the Porvincial_Safeguard flow.
> BCMOHAD-14191 New criteria added in  Rule 27

- MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
- MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
- MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
- MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
Flow : Mandatory Flow
Rule 20 : BCMOHAD – 14193
PR is already created before , only just condition change in decision box.
Current Logic : ((1 AND 2 AND 16  AND 3 AND 4 AND 5 AND 6 AND 7 AND 17 AND 9 AND 10 AND 11 AND 18 AND 19) OR (1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7 AND 8 AND 9 AND 10 AND 11 AND 20) AND (12 OR 13)) OR (14 AND 15)
Rule 25 : BCMOHAD -14195
Section: Palliative Care                                                                                                                                                                                                                        
New  field Added with Variable :-  Location of Palliative Care -  Location_of_Palliative_care__c.field-meta.xml  -{!Var1634_Location_of_Palliative_care} , Types of palliative care received - …
> BCMOHAD-14195 -Rule 20, 25,26,33,42,50 -Updates

- MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Flow Mandatory 
No New Variable Added for fields , Only decision logic change 
Rule : 42
We are missing one mandatory field for 2023+ cases (it should be “Written or verbal request date” and “Patient required palliative care?”
RULE 58 Exception (same exception as Rule 57 & 60) 
FORM 1633                                                                                                                                                                                                                                           
Rule 58: The following 1633 form fields must be completed for CASE field "Mandatory Data" Flow to close case required to close case Criteria: the fields listed are mandatory to close file: …
>  BCMOHAD-14461  || Rule  42 & 58 changes

- MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Mandatory Flow
Rule 46: If "1633 Form" field on 1634 form is TRUE AND "Case Type Reported Date" -/= 2022-12-31 OR (If “Case Type Reported Date” equal or greater than 2023-01-01 AND 1633 Form Entered on 1634 form is “True” Date of Assessment is less that 2023-01-01) THEN the following section are NOT mandatory on the 1634: Consulted other health care professionals, "Patient received palliative care", "Patient needs disability support service" AND “Patient required palliative care?”
Added Condition Logic  : 12 & 13
(  ( (1 AND 2) OR ( 1 AND 12 AND 4 AND 3 AND 13) )  AND ( 6 OR 7 OR 8) )  OR  5 OR  ( 9 AND 10 AND 11)
Older MAid Forms 2021 : No  & Not Blank
> BCMOHAD-14584 || Rule 46 Change

- MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
- MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Types_of_palliative_care_received__c.field-meta.xml
**Mandatory_Data.flow-meta.xml** 
**Objects/Form_1634__c/Fields/Types_of_palliative_care_received__c**
Rules 57, 58, 25 Updated.
**Rule 57, 58** : There were missing an exception to Bypass these rules so lara asked us to add an exception to bypass this rule for Maid death forseable and Maid death Not forseable cases.
**Rule 25**: There was Scenario failing whenever the field : "Types of Palliative care received" contains Other so this is fixed by changes the picklist value to "Other Care Service" 
Fixes # (issue)- BCMOHAD-14824
**Rule 57, 58** : There were missing an exception to Bypass these rules so lara asked us to add an exception to bypass this rule for Maid death forseable and Maid death Not forseable cases.
**Rule 25**: There was Scenario failing whenever the field : "Types of …
> BCMOHAD-14824 Rules 57, 58, 25 Updated

- MAiD - Case Management App/force-app/main/default/flows/Provincial_and_RX_Flow_for_1633.flow-meta.xml
Rule 60 Bypass exception added
Exception: If case type is "Discontinuation of Planning - Death Prior" OR  "Discontinuation of Planning - Patient Withdrawal" AND "1633 form entered" field is TRUE on the 1634 form OR If "1633 form" on case equal "No" THEN Rule 60 does not apply  
Fixes # (BCMOHAD-14463)
- [Yes] Bug fix (non-breaking change which fixes an issue)
Exception: If case type is "Discontinuation of Planning - Death Prior" 
OR 
"Discontinuation of Planning - Patient Withdrawal" 
AND 
"1633 form entered" field is TRUE on the 1634 form 
OR
If "1633 form" on case equal "No" THEN Rule 60 does not apply 
https://github.com/bcgov/MOH-MAiD/pull/619
> BCMOHAD-14463 Rule 60 Updated

- MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
.Rule 57 Updated:
the field on case "X1633__c"  is NotEqualTo Null condition added
Fixes # (BCMOHAD-14994)
the field on case "X1633__c"  is NotEqualTo Null condition added
> BCMOHAD-14994 Rule 57 Updated

- MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Rule 57 Updated:
the field on case "X1633__c" is NotEqualTo Null condition added
Fixes # (BCMOHAD-14995)
- [ YES] Bug fix (non-breaking change which fixes an issue)
the field on case "X1633__c" is NotEqualTo Null condition added
> BCMOHAD-14995 Rule 58 Update

- MAiD - Case Management App/force-app/main/default/flows/MAiD_Prevent_Duplicate_Phn.flow-meta.xml
This pull request includes change to fix duplicate PHN issue faced in higher environments. 
- Same PHN for different Case Type status !=> Closed is a PASS
- Same PHN for same cast type that is open would be FAIL. Stopping to saving and Error notification.
- Is the PHN equal to the same as Open MAID open assessment of eligibility. Then error notification otherwise PASS. (ONLY for MAiD Case type)
- Just on all closed cases, does PHN exists in previous cases. Show notification PASS.
https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-14981
- MAiD - Case Management App/force-app/main/default/flows/MAiD_Prevent_Duplicate_Phn.flow-meta.xml
> BCMOHAD-14981 || Fix Duplicate PHN flow.

- MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
“Withdrawal means to relieving suffering” if only required if 1634 field “if known, reasons for withdrawal” contains “Accepted the means to relieve their suffering” otherwise “Withdrawal means to relieving suffering” should be NULL.
Above Logic implemented
Fixes # (BCMOHAD-15040)
Withdrawal means to relieving suffering” if only required if 1634 field “if known, reasons for withdrawal” contains “Accepted the means to relieve their suffering” otherwise “Withdrawal means to relieving suffering” should be NULL.
Above Logic implemented
https://github.com/bcgov/MOH-MAiD/pull/629
> BCMOHAD-15040 Rule 50 Update

- MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
- MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/Where_was_the_substance_dispensed__c.field-meta.xml
Made the changes in Federal Safeguards flow in rule 19 as per Lara's recommendation.
Removed the Var1645_Finalwaiverofconsentdatesigned LessThan Var1634_MAiDAdministrationDate condition
Removed the Default value to the Where was the substance field in form 1641 object.
MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/Where_was_the_substance_dispensed__c.field-meta.xml
> BCMOHAD-16512-v1 || Updated Flow and form 1641 field

- MAiD - Case Management App/force-app/main/default/permissionsetgroups/MAiD_Manager_2_Group.permissionsetgroup-meta.xml
Deleting the Permission set group
**POST DeploymentStep:**
Delete **MAiD Manager 2** Group permission set group
MAiD - Case Management App/force-app/main/default/permissionsetgroups/MAiD_Manager_2_Group.permissionsetgroup-meta.xml
> BCMOHAD-24670 || Deleting the Manager 2 Permission set Group

- MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/validationRules/Rule_42_Data_Check.validationRule-meta.xml
- MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/Maid_Validation_Settings__c.object-meta.xml
- MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/fields/Case_Type_Reported_Date__c.field-meta.xml
Added validation rule on Object Form_1634__c
Added custom settings Maid_Validation_Settings__c with 1 field
Post Deployment Steps :
Navigate to settings -> Custom Settings -> Manage [Maid Validation Settings] -> 
Click New -> for field "Case Type Reported Date" select date as 2023-01-01
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/validationRules/Rule_42_Data_Check.validationRule-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/Maid_Validation_Settings__c.object-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/fields/Case_Type_Reported_Date__c.field-meta.xml
> BCMOHMAD-24595 || Val rule and custom settings

- MAiD - Case Management App/force-app/main/default/flows/ICY_Intake_Assign_To_Handler.flow-meta.xml
If the share record is already created , do not create a new share record.
Mary-Anna was trying to assign Intakes to clinical team members but got the error. 
Update flow to not create sharing record if already available.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing …
> Update Flow BCMOHAD-24781

- MAiD - Case Management App/force-app/main/default/flexipages/ICY_Referral_Record_Page.flexipage-meta.xml
- MAiD - Case Management App/force-app/main/default/flows/ICY_Intake_Reopen_Flow.flow-meta.xml
- MAiD - Case Management App/force-app/main/default/flows/Intake_Close_Flow.flow-meta.xml
- MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Is_Related_Intake_Closed__c.field-meta.xml
- MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
BCMOHAD-26373 -  Update reopen referral visibility
Fixes # (BCMOHAD-26373)
POST DEPLOYMENT STEPS TO RUN IN UAT,PROD ( QA ALREADY DONE)
================================================
To Update historical Data for Field  Is_Related_Intake_Closed__c on Referral Object follow below steps:
1) Disable all Active Validation Rules on Referral Object 
2) Run below Query to extract PROD Intake closed record:
select Id,Status__C from Intake__c where Status__c='Closed'
3) Run Data Import/update on same file extracted above 
4) Enable previously deactivated Validation Rules on Referral Object 
> BCMOHAD-26373 -  Update reopen referral visibility

- MAiD - Case Management App/force-app/main/default/classes/ICY_Notes_Documents_Controller.cls
Query running inside the for loop for the fetching the role for the current running user is moved out of the for loop and 101 SOQL Error-Governor Limit Fixed accordingly.
used a new boolean variable for checking the if the role of the current running user is program leader and passed into the for loop for the evaluation furthur
> BCMOHAM-21852 - 101 SOQL Error-Governor Limit Fixed in displaying the notes on the case.
