MAiD - Case Management App/.eslintignore, MAiD - Case Management App/.forceignore, MAiD - Case Management App/.gitignore, MAiD - Case Management App/.prettierignore, MAiD - Case Management App/.prettierrc, MAiD - Case Management App/.vscode/extensions.json, MAiD - Case Management App/.vscode/launch.json, MAiD - Case Management App/.vscode/settings.json, MAiD - Case Management App/README.md, MAiD - Case Management App/config/project-scratch-def.json, MAiD - Case Management App/dev-setup.bat, MAiD - Case Management App/force-app/main/default/aura/.eslintrc.json, MAiD - Case Management App/force-app/main/default/lwc/.eslintrc.json, MAiD - Case Management App/force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml, MAiD - Case Management App/manifest/package.xml, MAiD - Case Management App/package.json, MAiD - Case Management App/scripts/apex/hello.apex, MAiD - Case Management App/scripts/soql/account.soql, MAiD - Case Management App/sfdx-project.json
=> Bcmohad 4306

MAiD - Case Management App/.vscode/settings.json, MAiD - Case Management App/force-app/main/default/objects/Account/validationRules/Required_Account_first_Name.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/profiles/Admin.profile-meta.xml, MAiD - Case Management App/manifest/package.xml
Account First Name Required Validation Rule added
=> Bcmohad 3616

MAiD - Case Management App/Manifest/Package.xml, MAiD - Case Management App/force-app/main/default/layouts/Task-Task Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Account/validationRules/Required_Account_first_Name.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/College_ID__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/File_Creation_Date__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/profiles/Admin.profile-meta.xml, MAiD - Case Management App/manifest/package.xml
Merging QA fixes and deficiency resolutions
=> Bcmohad 4419

MAiD - Case Management App/force-app/main/default/profiles/Admin.profile-meta.xml, MAiD - Case Management App/force-app/main/default/profiles/MAiD Analyst.profile-meta.xml, MAiD - Case Management App/force-app/main/default/profiles/MAiD Manager.profile-meta.xml, MAiD - Case Management App/force-app/main/default/profiles/MAiD System Administrator.profile-meta.xml
BCMOHAD-4540: Updating user profiles for deployment
=> Bcmohad 4540

MAiD - Case Management App/force-app/main/default/objects/Account/fields/College_ID__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Account/validationRules/College_ID.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/PHN_Numeric_Only.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/workflows/Case.workflow-meta.xml
Custom field: PHN & College ID
Validation Rule: to check College ID is only numeric
=> MCMOHAD-4682

MAiD - Case Management App/force-app/main/default/profiles/MAiD Analyst.profile-meta.xml, MAiD - Case Management App/force-app/main/default/profiles/MAiD Manager.profile-meta.xml, MAiD - Case Management App/force-app/main/default/profiles/MAiD System Administrator.profile-meta.xml
=> Bcmohad 3678.rev01

MAiD - Case Management App/force-app/main/default/objects/Form_RXMAR__c/fields/IV_Drug_Regiment__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_RXMAR__c/fields/Phenobarbital_sodium_chloride__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_RXMAR__c/fields/proPOFol_sodium_chloride__c.field-meta.xml
Three fields updated in Form RX/MAR -
IV Drug   Regiment
Phenobarbital sodium chloride flush
proPOFol sodium chloride flush
=> Form RX/MAR Issues Fix

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
=> Permission Set to include Patient Name

MAiD - Case Management App/force-app/main/default/layouts/Form_1632__c-Form 1632 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1633__c-Form 1633 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1635__c-Form 1635 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1641__c-Form 1641 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1642__c-Form 1642 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_RXMAR__c-Form Rx%2FMAR Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/Error_Log.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
1. Permission sets changed to include the "Patient Name" field on Error Log
2. Case Type picklist valued set for each Record Type
3. Forms Layout changed to include Error Log in its related List
=> Bcmohad 3636

MAiD - Case Management App/force-app/main/default/objects/Case/listViews/All_Closed_Errors.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/listViews/All_Open_Cases.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/listViews/All_Open_Errors.listView-meta.xml
**Case List views** -
All Open Cases 
All Closed Cases
All Open Errors
All Closed Errors
=> List Views

MAiD - Case Management App/force-app/main/default/objects/Case/listViews/All_Closed_Errors.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/listViews/All_Open_Cases.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/listViews/All_Open_Errors.listView-meta.xml
Filter changed for List views - 
From My Cases -> All Cases
=> List View Filter changed

MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Nurse Practitioner.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Pharmacist.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Physician.layout-meta.xml
Updating Account layouts to One Column layout (BCMOHAD-5317)
=> Bcmohad 5317

MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Date_received_required_for_1645.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Date_received_required_for_RXMAR.validationRule-meta.xml
2 Validation rules are added for RX MAR & 1645 Date received
=> Bcmohad 5322

MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/fields/I_determine_that_the_patient__c.field-meta.xml
Added Picklist field question option " 4- NO determination made"
=> Added Picklist field

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
Updated field to 'ReadOnly' in layout. Please disregard previous field submitted.
=> Updated field to (ReadOnly)

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Error Log.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1632__c-Form 1632 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1633__c-Form 1633 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1635__c-Form 1635 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1641__c-Form 1641 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1642__c-Form 1642 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_RXMAR__c-Form Rx%2FMAR Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Nurse Practitioner.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Pharmacist.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Physician.layout-meta.xml
Updated buttons on layout page of objects. Will be submitting 5422 (Lightning Pages).
=> Layout Buttons

MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
Fields removed from the Layout of Form 1634 -
Recommendation   to seek advice on life insurance
Patient's natural death become reasonably foreseeable
Planned  location and time   for MAiD:
Planned Location for    MAiD
If Facility/Site, specify Facility and Unit within Facility
If Other location, specify
Planned Date
Days from Initial request (if less than 10 clear days)
Practitioner ensured 10 clear days
Practitioner reasons IF less than 10 clear Days:
=> Form 1634 Layout Changes - Hide Fields

MAiD - Case Management App/force-app/main/default/layouts/Form_1633__c-Form 1633 Layout.layout-meta.xml
Removed (Share) button from Page Layout 1633
=> Removed Share button from Page Layout

MAiD - Case Management App/force-app/main/default/layouts/Form_1632__c-Form 1632 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1632__c/fields/Requestor_initialed_Safeguards__c.field-meta.xml
=> Bcmohad 5507v2

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
ability to modify key fields on object
=> field access

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
=> update field permissions

MAiD - Case Management App/force-app/main/default/objects/Form_1632__c/validationRules/Form_1632_DoB_should_be_same_as_Case_DoB.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1632__c/validationRules/Form_1632_PHN_same_as_Related_Case.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/validationRules/Form_1633_DoB_should_be_same_as_Case_DoB.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/validationRules/Form_1633_PHN_same_as_Related_Case.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/validationRules/Form_1634_DoB_should_be_same_as_Case_DoB.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/validationRules/Form_1634_PHN_same_as_Related_Case.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1635__c/validationRules/Form_1635_DoB_should_be_same_as_Case_Do.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1635__c/validationRules/Form_1635_PHN_same_as_Related_Case.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/validationRules/Form_1641_DoB_should_be_same_as_Case_DoB.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/validationRules/Form_1641_PHN_same_as_Related_Case.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1642__c/validationRules/Form_1642_DoB_should_be_same_as_Case_Do.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1642__c/validationRules/Form_1642_PHN_same_as_Related_Case.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1645__c/validationRules/Form_1645_DoB_should_be_same_as_Case_Do.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1645__c/validationRules/Form_1645_PHN_same_as_Related_Case.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_RXMAR__c/validationRules/RXMAR_DoB_should_be_same_as_Case_DoB.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_RXMAR__c/validationRules/RXMAR_PHN_same_as_Related_Case.validationRule-meta.xml
PHN and DoB to be validated against the case
Total forms - 8
Total Validation Rules - 16 (2 validation rules per form)
=> PHN and DoB to be validated against the case

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reporting_Errors__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Types_of_Reporting_Errors__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Which_part_of_form_1633_was_missed__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
=> Bcmohad 5490v13

MAiD - Case Management App/force-app/main/default/objects/Case/businessProcesses/MAiD Case.businessProcess-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/Error_Log.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/MAiD_Case.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/standardValueSets/CaseStatus.standardValueSet-meta.xml, MAiD - Case Management App/force-app/main/default/standardValueSets/CaseType.standardValueSet-meta.xml
=> Revert "Case Status and Type Field values changes"

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Education_provided_on_case__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Federal_Safeguards__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Legislation_and_Critical_Safeguards__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Manager_Override_Requested__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Mandatory_Data__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Notes_to_Manager__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Provincial_Safeguards__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Date_of_MAiD_Required_Rule.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/If_Yes_is_patients_change_in_eligbilit__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/If_Yes_practitioner_became_aware_patien__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Practitioner_previously_determined_patie__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Request_Province_was_received__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/X1633_Form_entered__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
=> Bcmohad 6206

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
Update in Case-MAiD Case Layout, added Practitioner College ID field
=> Added Practitioner CollegeID Case-MAiD Case Layout

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/SLF_S30_Formula__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S2_Self_Administration_v1_a28.report-meta.xml
note Manager Profile had a lot of fields not checked, this has been updated in this Manager Perm Set
=> update S2 Report

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Updates to Rule 44 45 4 50 51 55 based on the recent discussions
=> Update in 6200 Flow Mandatory Data

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Federal_Safeguards_Feedback__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Added Flow of Federal Safeguard,
Field on Case
Permission Sets based on Feedback Field
=> Updates regarding Federal Safeguard Rules

MAiD - Case Management App/force-app/main/default/flows/MAiD_Case_Stage_Changes_AFTER.flow-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/MAiD_Death_Foreseeable_Status.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/MAiD_Death_Not_Foreseeable_Status.validationRule-meta.xml
Fixing initial testing feedback
=> Bcmohad 5891 4

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Final_waiver_of_consent_date_signed__c
Edit access granted to this field on Form 1645
=> Update to MAiD Analyst, MAiD Manager, MAiD Sys Admin PM

MAiD - Case Management App/force-app/main/default/flows/Status_4_update.flow-meta.xml, MAiD - Case Management App/force-app/main/default/flows/Status_Change_CC_Review_Checks_In_Progress.flow-meta.xml
New status 4 flow incorporated and deactivated earlier flow
=> Status 4 updates.

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml, MAiD - Case Management App/force-app/main/default/flows/check_for_existing_open_case_with_same_PHN.flow-meta.xml
BCMOHAM-6162 Updates related to duplicate PHN Issue. Fixed the flow filters to get records.
BCMOHAD-8284 Fixed the greater than field Rule 38 of Federal Safeguards
=> Updates related Duplicate PHN and Federal Safegrds

MAiD - Case Management App/force-app/main/default/objects/Contact/fields/Notes__c.field-meta.xml
Updated the field size to 3000
=> Updated Field Size to 3000

MAiD - Case Management App/manifest/package.xml
Custom notification added to Package XML.
=> Adding Custom Notification To package XML

MAiD - Case Management App/manifest/package.xml
Duplicate Notification Builder added to Package XML.
=> Bcmohad 8903

MAiD - Case Management App/manifest/destructiveChangesPost.xml
desctuctiveChangePost.xml added
=> desctuctiveChangePost.xml added

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Removal of rule 41 from the federal safeguard flow.
=> removal of Rule 41

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Record_ID - Formula from Case Permission Sets
=> Updated and removed

MAiD - Case Management App/manifest/destructiveChangesPost.xml, MAiD - Case Management App/manifest/destructiveChangesPre.xml
destructiveChangesPost.xml and destructiveChangesPre.xml got updated
=> destructiveChangesPost.xml and destructiveChangesPre.xml got updated

MAiD - Case Management App/force-app/main/default/flows/Provincial_and_RX_Flow_for_1633.flow-meta.xml
Changes for invalid reference Flow.
=> Changes for the invalid reference RX_Flow

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Rule 57 and Rule 58 fixed based on issues raised by Lara
=> Fix to Mandatory Data flow in QA

MAiD - Case Management App/force-app/main/default/flows/Provincial_and_RX_Flow_for_1633.flow-meta.xml
Changes and fixes suggested on Rule 65.
=> Final changes for Rule 65 after Lara's Feedback

MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Health_Canada_Reportable_Date_validation.validationRule-meta.xml
Deactivated validation rule Health Canada Validation Rule
=> Updated the validation rule

MAiD - Case Management App/force-app/main/default/flexipages/Practitioner_Page.flexipage-meta.xml
=> Added Flexi page updates for Practitioner Record

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1645__c-Form 1645 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1645__c/fields/Agreed_date_of_MAiD__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Changes to the Rule 19:-
- Addition of new field " Agreed date of Maid"
- Changes to the Layout of 1645 for addition of the field
- Changes to the permission sets
- Changes to the Flow Rule 19 in Federal Safeguard Flow
=> Changes to the Rule 19 - Federal Safeguards Flow

MAiD - Case Management App/force-app/main/default/flows/display_warning_for_duplicate_phn.flow-meta.xml
PR for PHN Duplication Changes.
=> Changes to the duplication of PHN Rule

MAiD - Case Management App/sfdx-project.json
update sfdx-project.json to reflect latest package version
=> update sfdx-project.json to reflect latest package version

MAiD - Case Management App/force-app/main/default/flows/display_warning_for_duplicate_phn.flow-meta.xml
Changes to Incorporate the changes for MAiD Assessment of Eligibility in PHN Duplication Rule.
=> Changes to include MAiD Assessment of Eligibility

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Changes to the Rule 19 for adjusting "MAiD Admin date" and "Agreed Date of MAiD" validations.
=> Changes to the Rule 19 for MAiD Admin Date check

MAiD - Case Management App/sfdx-project.json
update sfdx-project.JSON to reflect the latest Release 1.9.4
=> update sfdx-project.JSON to reflect the latest Release 1.9.4

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/SUP_Q05__c.field-meta.xml
Update to SUP+Q05 field based on discussions with Lara Supplementary field info issue
=> Update to SUP_Q05 field

MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/Where_was_the_substance_dispensed__c.field-meta.xml
Default Value for Field is removed.
=> Default Value Updated

MAiD - Case Management App/force-app/main/default/objects/Case/businessProcesses/MAiD Case.businessProcess-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/compactLayouts/MAiD_Case_Layout.compactLayout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Daily_Activity_Limits__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Identify_as_Indigenious__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_1630_Incomplete__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Months__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Other_Living_Arrangement_Specify__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Private_Residence_Living_arrangement__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Sex_Other_specify__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Years__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_yes_Indigenious_heritage__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_yes_types_of_disabilites__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Length_of_Disability__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Older_MAiD_Forms_to_2021__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Other_Residence_Specify__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Other_long_term_condition_specify__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Racial_Ethinic_or_Cultural_Group__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Requestor_disability_opinion__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Sex_at_Birth__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Usual_Place_of_Residence__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/X1630_Date_Received__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/X1630__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/MAiD_Case.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/standardValueSets/CaseType.standardValueSet-meta.xml
Added the new Fields
Created New sections in Page layouts
Made changes in the permission sets
=> Added Fields, Layout, Permission set

.gitignore, MAiD - Case Management App/.forceignore, MAiD - Case Management App/.sf/config.json, MAiD - Case Management App/README.md, MAiD - Case Management App/force-app/main/default/layouts/Form_1645__c-Form 1645 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1645__c/fields/Verbal_Consent__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
2023 Reporting Regulations - 1645 FORM – New field “Verbal Consent” Box (True/False)
> Custom Object: Form 1645
Custom Fields: objects/Form_1645__c/fields/Verbal_Consent__c.field-meta.xml
> Permission Sets:
- /permissionsets/MAiD_Analyst.permissionset-meta.xml
- /permissionsets/MAiD_Manager.permissionset-meta.xml
- /permissionsets/MAiD_System_Administrator.permissionset-meta.xml
=> BCMOHAD-13395 || Changes to include new field

MAiD - Case Management App/force-app/main/default/flows/Provincial_and_RX_Flow_for_1633.flow-meta.xml
=> Update Rule 63

MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
=> BCMOHAD-13389||Fix page layout issues when merging

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
2023 Reporting Regulations - Flow Rule 44 update
> FlowName: Mandatory_Data
Changed Rule 44 decision condition.
=> BCMOHAD-13387 || Remove rule 44 condition

MAiD - Case Management App/force-app/main/default/flows/Provincial_and_RX_Flow_for_1633.flow-meta.xml
Flow Change is Updated to related -BCMOHAD13388
=> BCMOHAD-13388 - Flow Change -PS and RXMAR

MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/If_Prior_Request_outcome__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/If_no_confirm__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/If_no_date_of_death__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/If_yes_date_of_death__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/If_yes_select_all_that_apply_1__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Location_of_Palliative_care__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Patient_has_discussed_and_considered_mea__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Specify_expert_specialty_if_Other__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Specify_other_withdrawal_reason__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Who_did_you_receive_the_written_request__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Added 2 new fields
Updated some new fields with help text, and Picklist values, Updated the Page layout
Updated the permission set
=> BCMOHAD-13385-v1 || Updated the changes as per request

MAiD - Case Management App/force-app/main/default/layouts/Form_1632__c-Form 1632 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1632__c/fields/Consent_to_contact_for_organ_donor_info__c.field-meta.xml
Created a new picklist field and added it to page layout
=>  BCMOHAD-13586 || Created new field and added to page layout

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
=> Bcmohad 13384 v1 || Updated the pagelayout

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
=> Bcmohad 13586 v1 || added missing permission sets

MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Potential_BCCS_Review__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
created new field and updated page layout
=> Bcmohad 13587 || created new field and updated page layout

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
2023 Reporting Regulations - 2 CASE FIELDS TO RELOCATE
> Object: Case
Page Layout : force-app\main\default\layouts\Case-MAiD Case Layout.layout-meta.xml
=> BCMOHAD-13615: Update Field locations

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Added the missing Field permission
=> BCMOHAD-13384-v2 || Updated the Permission set for the missing field

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/If_No_why_not_voluntary__c.field-meta.xml
=> BCMOHAD-13385-v2 || Updated the Field

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Potential_BCCS_Review__c.field-meta.xml
updated help text and description
=> Bcmohad 13587|| updated help text and description

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Other_Race_Specify__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Created the New Field
Updated the Page layout
Updated the Permission Sets
=> BCMOHAD-13649 || Created the New field, Updated the Page layout

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/X1633_Form_entered__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/X1634_Old_form__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Created new field and updated permission sets
=> Bcmohad 13648 v1|| Created new field and updated permission sets

MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
Jira Ticket Number: BCMOHAD-13396
List Of Changes:
Updated the page layout with old form field 
Object: Form 1634
=> Bcmohad 13396-v2|| Added field to the page layout

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Patient_desc_suffering_If_yes_select_all__c.field-meta.xml
Jira Ticket Number: BCMOHAD-13652
List of changes:
Object: Form 1634
Updated a picklist value in the field"Patient_desc_suffering_If_yes_select_all__c(If yes, select all that apply)"
=> BCMOHAD-13652 || Added "existential" in the picklist value

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Usual_Place_of_Residence__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/MAiD_Case.recordType-meta.xml
Jira Ticket Number: BCMOHAD-13884
List of changes:
Object: Case
Updated a new field "Usual_Place_of_Residence__c.field-meta.xml"
Updated the record type "MAiD_Case.recordType-meta.xml"
=> BCMOHAD-13884 || Added the Do not know value

MAiD - Case Management App/force-app/main/default/layouts/S1_HC_2023__c-S1 HC 2023 Layout.layout-meta.xml
2023 Reporting Regulations - Remove Case field from Page Layout
> Page Layout: Remove Case field from Page layout which was added before.
S1_HC_2023__c-S1 HC 2023 Layout.layout-meta.xml
=> BCMOHAD-14029 - Remove Case field from Page Layout

MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Other_relief_means_specify__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Withdrawal_means_to_relieve_suffering__c.field-meta.xml
1634 OBJECT : ticket BCMOHAD - 14060
I added 2 fields :  
Meta data : Withdrawal_means_to_relieve_suffering__c.field-meta.xml
Withdrawal means to relieve suffering - Withdrawal_means_to_relieve_suffering__c
Meta data : Other_relief_means_specify__c.field-meta.xml
Other relief means, specify: ** - Other_relief_means_specify__c
And
Page Layout : 1634 form
Meta data : Form_1634__c-Form 1634 Layout.layout-meta.xml
=> BCMOHAD-14060 || 1634 object - Field Added & Hide,Pagelayout

MAiD - Case Management App/force-app/main/default/layouts/Form_1645__c-Form 1645 Layout.layout-meta.xml
Just 1645 Page layout Changes
1645 Page layout : Metadata : Form_1645__c-Form 1645 Layout.layout-meta.xml
=> BCMOHAD-14092 -V1 || 1645 Page layout Changes

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/S1_HC_2023__c.object-meta.xml
2023 Reporting Regulations - Renamed Custom Object name
> Custom Object XML: Rename new custom object name from S1 HC 2023 Report Template to HC2023 Reporting Fields
S1_HC_2023__c.object-meta.xml
=> BCMOHAD-14095 || Rename Custom object Name

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Deployment Tracker to Related ticket [BCMOHAD-14060] (https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-14060)
Added Permisson  for MAid Analyst, Manager & System Administrator.
=> BCMOHAD-14060-V2 || Added Permission sets

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SEX_Q05__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SEX_S05__c.field-meta.xml
2023 Reporting Regulations - Removed Sex fields that were removed earlier.
> Removed old Sex Fields that were renamed.
=> BCMOHAD-14029 V2 || Remove sex fields

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
##Description
Remove MDR1_Q05__c fields from Permission set and other metadata so that it does not affect other team members PR.
=> BCMOHAD-14029 || Remove MDR1_Q05__c field from metadata.

MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
Deployment Tracker : 
Page Layout : Form_1634__c-Form 1634 Layout.layout-meta.xml
=> BCMOHAD - 14126 Updated Page Layout

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40A__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40B__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40C__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40D__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40E__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40F__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40G__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40H__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40I__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40J__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_S40I__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Reports_Dashboards.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
Fields :
1. Object : S1_HC_2023__c Field : COD_Q40A__c.field-meta.xml S1_HC_2023__c
2. Object : S1_HC_2023__c Field : COD_Q40B__c.field-meta.xml S1_HC_2023__c
3. Object : S1_HC_2023__c Field : COD_Q40C__c.field-meta.xml S1_HC_2023__c
4. Object : S1_HC_2023__c Field : COD_Q40D__c.field-meta.xml S1_HC_2023__c
5. Object : S1_HC_2023__c Field : COD_Q40E__c.field-meta.xml S1_HC_2023__c
6. Object : S1_HC_2023__c Field : COD_Q40F__c.field-meta.xml S1_HC_2023__c
7. Object : S1_HC_2023__c Field : COD_Q40G__c.field-meta.xml S1_HC_2023__c
8. Object : S1_HC_2023__c Field : COD_Q40H__c.field-meta.xml S1_HC_2023__c
9. Object : S1_HC_2023__c Field : COD_Q40I__c.field-meta.xml S1_HC_2023__c
10. Object : S1_HC_2023__c Field : COD_Q40J__c.field-meta.xml S1_HC_2023__c
11. …
=> BCMOHAD-14077||Added New Formula Fields

MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
Deployment Tracker 
1. Report Type :Form_1634_with_S1_HC_2023.reportType-meta.xml
2. Report : MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
=> BCMOHAD-14077 || Updated Report Type

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Deployment tracker.
Rule 45 Change , Flow Name is Mandatory Data
Meta data name : Mandatory_Data.flow-meta.xml
=> BCMOHAD-14093 || Rule 45 Change

MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
Deployment Tracker : 
1. Report : MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
=> BCMOHAD-14077||Changed position of few fields

MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
BCMOHAD-14192-New Criteria added in the Rule29
=> Bcmohad 14192

MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Legislation_Safeguards.flow- Rule 3 Success and failure Criteria updated
=> BCMOHAD-14177 Rule 3 Updated

MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
Rule 27 Updated with year criteria-Potential_BCCS_Review field Applicable from 2023-01-01
=> BCMOHAD-14191

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Deployment Tracker: 
flows : Federal_Safeguards.flow-meta.xml
=> BCMOHAD-14183||updated flow

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
flows:Federal_Safeguards.flow-meta.xml
=> BCMOHAD- 14186||Updated Flow

MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml
Report:
MAiD - Case Management App/force-S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml
=> BCMOHAD-14076 || Added Supplementary Info field in the report

MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
=> BCMOHAD-14192 Rule 29 Updated

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
=> BCMOHAD-14185 Rule 12 Updated

MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
=> BCMOHAD-14192

MAiD - Case Management App/.sf/config.json, MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
Add missing report type.
- Form_1634_with_S1_HC_2023.reportType-meta.xml
=> BCMOHAD-14075 v1 || Add missing report type file

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Deployment Tracker
flows : Federal_Safeguards.flow-meta.xml
=> Bcmohad 14183 || updated rule

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/SLF_Q11__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/SLF_S11__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SLF_Q45__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SLF_Q50__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S2_2023_HC_ReportOral_MAiD_P8M.report-meta.xml
fields:
SLF_Q11__c.field-meta.xml
SLF_S11__c.field-meta.xml
SLF_Q45__c.field-meta.xml
SLF_Q50__c.field-meta.xml
Report Type:
Form_1634_with_S1_HC_2023.reportType-meta.xml
Report:
MAiDCaseManagementReports/S2_2023_HC_ReportOral_MAiD_P8M.report-meta.xml
Permission Set:
MAiD_Analyst.permissionset-meta.xml
MAiD_Manager.permissionset-meta.xml
MAiD_System_Administrator.permissionset-meta.xml
=>  BCMOHAD-14074||added fields and changed report

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Services_offered_or_discussed__c.field-meta.xml
BCMOHAD- 14187 Rule 37 Updated
=> BCMOHAD- 14187 Rule 37 Updated

MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Updated Flow:
Legislation_Safeguards.flow-meta.xml
Updated Rule 7
=> BCMOHAD-14181 || Updated Rule 7

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
flows:Federal_Safeguards.flow-meta.xml
=> BCMOHAD - 14190||Added rule 66

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
=> BCMOHAD-14184 Rule 11 Update

MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
=> BCMOHAD-14178 Rule 4 Update

MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
=> BCMOHAD-14179 Rule 5 Update

MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
=> BCMOHAD-14191 Rule 27 Update

MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
=> BCMOHAD-14180 Rule 6 Update

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Mandatory flow..! 
There is Rule 20 change , that i can see in it..! do i need to create PR again or this is good for review ?
=> BCMOHAD-14195 | Rule 25

MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Flow: Legislation_Safeguards.flow-meta.xml
Updated rule 47
=> BCMOHAD-14182 || Updated rule 47

MAiD - Case Management App/.sf/config.json, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/X1641_2023_Pharmacist_Report_Y6x.report-meta.xml
2023 Reporting Regulations - Add 1641 - 2023 Pharmacist Report.
> Change report type for the report.
Report:
- X1641_2023_Pharmacist_Report_Y6x.report-meta.xml (Update)
=> BCMOHAD-14078 v2 || Change Report type used in report as per Lara feedback

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
=> BCMOHAD-14190 Rule 66 Update

MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Updated a Flow: Legislation_Safeguards.flow-meta.xml
=> BCMOHAD-14182-v1 || Updated Rule 47

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Mandatory Flow : Rule 45 : Just change condition in decision box.
=> BCMOHAD-14379 || Rule 45 Change

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Updated the Existing flow.
Flow: Mandatory_Data.flow-meta.xml
=> BCMOHAD-14202 || Rule 57 update

MAiD - Case Management App/force-app/main/default/flows/Status_5_update_flow.flow-meta.xml
BCMOHAD-14208 Status 5 flow Update
=> BCMOHAD-14208 Status 5 flow Update

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
=> BCMOHAD-14204 Rule 68 Update

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
=> BCMOHAD-14205 Rule 69 Update

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Mandatory Flow , No new Field Added only Condition logic change
1634 FORM:                                                                                                                                                                                                                                         
Rule 46: 
-	IF ( "1633 Form entered " field on 1634 form is “TRUE” AND "Case Type Reported Date" less = 2022-12-31) 
OR  
-    ("1633 Form entered” field on 1634 form is “TRUE” AND  (Case field) "Older MAiD Forms to 2021" equal "Yes” AND "Case Type Reported Date" greater = 2023-01-01) 
-	the following section are NOT mandatory: 
(1634)	Consulted other health care professionals, "Patient received palliative care" AND "Patient needs disability support service"
BY PASS: If “1633 form …
=> BCMOHAD-14200 || Rule 46

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
=> BCMOHAD-14184 Rule 11 Fix

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
=> BCMOHAD-14190 Rule 66 Fix

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Flow : Mandatory 
Note : No new variable Added..!
1634 FORM:                                                                                                                                                                                                                                         
Rule 46: 
-	IF ( "1633 Form entered " field on 1634 form is “TRUE” AND "Case Type Reported Date" less = 2022-12-31) 
OR  
("1633 Form entered” field on 1634 form is “TRUE” AND  (Case field) "Older MAiD Forms to 2021" equal "Yes” AND "Case Type Reported Date" greater = 2023-01-01) 
-	the following section are NOT mandatory: 
(1634)	Consulted other health care professionals, "Patient received palliative care" AND "Patient needs disability support service"
BY PASS: If “1633 form entered” field is FALSE …
=>  BCMOHAD-14200-V1  || Rule 46 Changes

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
BCMOHAD-14204 Position of the Rules 67,68,69 Changed in the flow
=> BCMOHAD-14204 Position of the Rules 67,68,69 Changed in the flow

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
BCMOHAD-14204 Position error fixed
=> BCMOHAD-14204 Position error fixed

MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Updated a Flow: Legislation_Safeguards.flow-meta.xml
=> BCMOHAD-14182-v1 || Updated the changes

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
BCMOHAD-14462 Rule 48 Not Applicable from 2023 criteria added
=> BCMOHAD-14462 Rule 48 Not Applicable from 2023 criteria added

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
BCMOHAD-14204 Rule 68, 69 Update
=> BCMOHAD-14204 Rule 68, 69 Update

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
BCMOHAD-14462 Rule 48 Bypass Rule changes Reverted
=> BCMOHAD-14462 Rule 48 Bypass Rule changes Reverted

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Preferred_Gender__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RAC_Q05I__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S2_2023_HC_ReportOral_MAiD_P8M.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
This pull request contains changes to S1, S2 and other reports highlighted by Lara.
https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-14385
- Add missing fields on Case/Form 1634.
- Fix Picklist field that had extra space.
- Add fields in the correct order.
Custom Fields
1. MAiD - Case Management App/force-app/main/default/objects/Case/fields/Preferred_Gender__c.field-meta.xml
2. MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RAC_Q05I__c.field-meta.xml
Reports
1. MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S2_2023_HC_ReportOral_MAiD_P8M.report-meta.xml
2. MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml
3. MAiD - Case Management …
=> BCMOHAD-14385 || Fix report fields issue

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
BCMOHAD-14584 Rule 46 Changes reverted to Original Version
=> BCMOHAD-14584 Rule 46 Changes reverted to Original Version

MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Error Log.layout-meta.xml
Added the Health Authority field in the Error Log page layout and Updated the flow for updating the Health Authority field to automatically update from the parent case when the case parent is selected.
i.e., whenever we are creating a child case if we select the parent case then the Health Authority field value in the parent case will automatically be updated when the child case is saved
Updated the Flow: Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow
Updated the Page layout: Case-MAiD Error Log.layout
=> BCMOHAD-14354 || Added Page layout and the flow

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Types_of_palliative_care_received__c.field-meta.xml
PickList Label change as Part of Rule 25 Update
Fixes # (BCMOHAD-14824)
- [ YES] Bug fix (non-breaking change which fixes an issue)
=> BCMOHAD-14824 Picklist Label Change for Rule 25 Update

MAiD - Case Management App/.sf/config.json, MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/ELG_Q85_Formula__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/ELG_Q90_Formula__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_assessment_period__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/SLF_S11__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q40A__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q40B__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q51I__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q86A__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q87J__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_S72G__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SLF_Q50__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SPC_Q16__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SPC_S16__c.field-meta.xml
This Pull request consists of changes that were reported by lara.
- SPC_Q16 should be pulling from 1634 object "SPC_Q10 - Formula - Values"
- SPC_S16 should be pulling from 1634 object "SPC_S10 - Formula"
- ELG_Q40A is not populating a "1" if the bucket list contains "Cancer"
- ELG_Q40B is not populating a "1" if the bucket list contains "Neurological"
- ELG_Q51I is not populating a "1" if the bucket list contains "Emotional distress/anxiety/fear/existential suffering"
- ELG_S72G is not pulling from "Specify, expert specialty if Other" field on 1634
- ELG_Q85 -Formula (is pulling from the wrong field and should be pulling from "If no, was palliative care accessible?" - This is an issue that CGI has never fixed)
- ELG_Q86A is not populating a "1" when Home-based is selected in the bucket …
=> BCMOHAD-14824 || Fix Formula fields.

MAiD - Case Management App/force-app/main/default/globalValueSets/Missed_Error_Log_Issue.globalValueSet-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Impacted_Form__c.field-meta.xml
Updated the Global Value for MAiD Error log case and removed some picklist values from one of the field according to Lara's request .
Updated the Missed_Error_Log_Issue.globalValueSet-meta.xml
Updated the Impacted_Form__c.field-meta.xml
=> BCMOHAD-14236 || Updated the Global Picklist Valueset

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Rule 68 Update New Condition added and adjusted to meet the requirements
Fixes # (BCMOHAD-14985)
- [ YES] Bug fix (non-breaking change which fixes an issue)
- Identify as indigenious AND if "Identify as Indigenious" equals "Yes" THEN "If yes, indigenious heritage" is Mandatory
- ((Racial, Ethnic, or Cultural Group is Null) OR (Racial, Ethnic, or Cultural Group AND IF "Racial, Ethnic, or Cultural Group" contains "Other race" then "If Other Race, Specify:" is Mandatory )) 
https://github.com/bcgov/MOH-MAiD/pull/620
=> BCMOHAD-14985 Rule 68 Update

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Rule 48 Update New Bypass exception Added for 2023-01-01 cases.
Fixes # (BCMOHAD-14984)
Rule 48 Update New Bypass exception Added for 2023-01-01 cases.
https://github.com/bcgov/MOH-MAiD/pull/621
=> BCMOHAD-14984 Rule 48 Update

MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml, MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
--Rule 66 conditions changed
New fields added in the condition
--Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta condition logic changed
Just the existing logic modified No new conditions added
Fixes # (BCMOHAD-14824)
--Rule 66 conditions changed
New fields added in the condition
--Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta condition logic changed
Just the existing logic modified No new conditions added
https://github.com/bcgov/MOH-MAiD/pull/626
=> BCMOHAD-14824 Rule 66 and Health Canada Rule Update

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Rule 66 fix
Fixes # (BCMOHAD-14824)
Just Rule 66 Logic fixed
https://github.com/bcgov/MOH-MAiD/pull/627
=> BCMOHAD-14824 Rule 66 fix

MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
Fields added to the 1634 Page Layout: 
Practitioner_previously_determined_patie__c
If_Yes_is_patients_change_in_eligbilit__c
If_Yes_practitioner_became_aware_patien__c
Fixes # (BCMOHAD-15036)
Fields added to the 1634 Page Layout: 
Practitioner_previously_determined_patie__c
If_Yes_is_patients_change_in_eligbilit__c
If_Yes_practitioner_became_aware_patien__c
https://github.com/bcgov/MOH-MAiD/pull/628
=> BCMOHAD-15036 Fields added to the 1634 PageLayout

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-15057
force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
=> BCMOHAD-15057 || Move fields in page layout.

MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/PHA_Q16__c.field-meta.xml
PHA_Q16 formula field updated on Form_1641__C Object
New formula: CASE(Case__r.Practitioner_Name__r.PersonContact.Account.RecordType.Name, &quot;Pharmacist&quot;,1,0)
Fixes # (BCMOHAD-15036)
PHA_Q16 formula field updated on Form_1641__C Object
New formula: CASE(Case__r.Practitioner_Name__r.PersonContact.Account.RecordType.Name, &quot;Pharmacist&quot;,1,0)
=> BCMOHAD-15036 PHA_Q16 formula field updated on Form_1641__C Object

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Missed_Issue_on_Form_RX_MAR__c.field-meta.xml
"Medication dosage/time" value added to the "Missed Issue on Form RX/MAR field" picklist in the error log record time
Fixes # (BCMOHAD-15072)
"Medication dosage/time" value added to the "Missed Issue on Form RX/MAR field" picklist in the error log record time
=> BCMOHAD-15072 Medication dosage/time value added to the "Missed Issue on Form RX/MAR field" picklist

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Rule 50 logic change(minor change)
Allow Rule 50 to pass through If_known_reasons_for_withdrawal does not contain Accepted the means to relieve their suffering
Fixes # (BCMOHAD-15040)
Rule 50 logic change(very minor change)
Allow Rule 50 to pass through If_known_reasons_for_withdrawal does not contain Accepted the means to relieve their suffering
=> BCMOHAD-15040 Rule 50 Update

MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/PHA_Q16__c.field-meta.xml
BCMOHAD-15036 PHA_Q16 field formula update on Form 1641
Fixes # (BCMOHAD-15036)
New Formula: CASE(Dispensing_Pharmacist__r.RecordType.Name,"Pharmacist",1,0)
https://github.com/bcgov/MOH-MAiD/pull/635
=> BCMOHAD-15036 PHA_Q16 field formula update on Form 1641

MAiD - Case Management App/force-app/main/default/flows/MAiD_Prevent_Duplicate_Phn.flow-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
This pull request consists of changes to PHN duplicate rule. In the past, there were two flows that covered the scenarios but this change was to combine both flows into one and show the warning message and also prevent case update.
https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-15037
force-app/main/default/flows/MAiD_Prevent_Duplicate_Phn.flow-meta.xml
=> BCMOHAD-15037 || Update duplicate PHN rule

MAiD - Case Management App/.forceignore, MAiD - Case Management App/force-app/main/default/duplicateRules/PersonAccount.Duplicate_College_Id_Check.duplicateRule-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Nurse Practitioner.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Other Health Care Professionals.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Pharmacist.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Physician.layout-meta.xml, MAiD - Case Management App/force-app/main/default/matchingRules/PersonAccount.matchingRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/PersonAccount/recordTypes/Nurse_Practitioner.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/PersonAccount/recordTypes/Other_Health_Care_Professionals.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/PersonAccount/recordTypes/Pharmacist.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/PersonAccount/recordTypes/Physician.recordType-meta.xml
The issue we are having is we have 3 colleges (Physicians, Nurse Practitioners, and Pharmacists). Now that we have a large amount of each in our database were are running into the issue that some of the colleges have the same number of digits for their college ID numbers; Hence we have physicians and Pharmacists with the same college ID but different colleges.
So, as per Herman's suggestion, we have added a Type field in the layout, and as per ZAK's request, the Type field will have only one dropdown value for each layout. 
- Added Type Field in the Layout
MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Nurse Practitioner.layout-meta.xml
MAiD - Case Management App/force-app/main/default/layouts/PersonAccount-Other Health Care …
=> BCMOHAD-15545 || Added Page layout, Record type & Matching Rule

MAiD - Case Management App/force-app/main/default/classes/TestDataFactory.cls-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/Two_factor_Authentication.permissionset-meta.xml
Added the Two Factor Authentication Permission set to configure MFA
Added MFA Permission set
Added TestDataFactory-meta.xml file
MAiD - Case Management App/force-app/main/default/classes/TestDataFactory.cls-meta.xml
MAiD - Case Management App/force-app/main/default/permissionsets/Two_factor_Authentication.permissionset-meta.xml
=> BCMOHAD-16536-v1 || MFA Permission set and added missing test.xml file

MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls, MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerifyTest.cls, MAiD - Case Management App/force-app/main/default/classes/TestDataFactory.cls
It is behaving weird in qa because of try-catch, exception is being thrown and caught in catch block but it is not stopping from record to save, anyway we do not need to handle exception in our case, so removed the try-catch
MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls
MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerifyTest.cls
MAiD - Case Management App/force-app/main/default/classes/TestDataFactory.cls
=> BCMOHAD-16891-v1 || Removed the try-catch

MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml, MAiD - Case Management App/force-app/main/default/flows/MAiD_Flows_Q40_41_42.flow-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Form_1633__c-Form 1633 Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/File_Creation_Date__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Preferred_Gender__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_assessment_period__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/PROC_Q75_Formula__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05A__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05B__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05C__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05D__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05E__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05F__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/PROC_Q185C__c.field-meta.xml
Updated the Maid flow q4041 flow for the report fields, and federal Safeguards flow for rule 38.
Updated the IND_Q05A__c.field-meta.xml, IND_Q05B__c.field-meta.xml, IND_Q05C__c.field-meta.xml, IND_Q05D__c.field-meta.xml, IND_Q05E__c.field-meta.xml, IND_Q05F__c.field-meta.xml.
Updated the Length_of_assessment_period__c.field-meta.xml, File_Creation_Date__c.field-meta.xml, Preferred_Gender__c.field-meta.xml, PROC_Q75_Formula__c.field-meta.xml,  PROC_Q185C__c.field-meta.xml
Updated the Form_1633__c-Form 1633 Layout.layout-meta.xml
MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
MAiD - Case Management App/force-app/main/default/flows/MAiD_Flows_Q40_41_42.flow-meta.xml
MAiD - Case Management …
=> BCMOHAD-16712 || Updated the Fields, flows

MAiD - Case Management App/force-app/main/default/standardValueSets/AccountType.standardValueSet-meta.xml
Updated the Standard Value set Field "Account Type"
MAiD - Case Management App/force-app/main/default/standardValueSets/AccountType.standardValueSet-meta.xml
MAiD - Case Management App/force-app/main/default/standardValueSets/AccountType.standardValueSet-meta.xml
=> BCMOHAD-15545-v1 || Updating the Standard Value Set which was missing

MAiD - Case Management App/force-app/main/default/flows/MAiD_Flows_Q40_41_42.flow-meta.xml
Updated the flow with the condition where the record can save if we have provided the field with other values which are not in this flow
MAiD - Case Management App/force-app/main/default/flows/MAiD_Flows_Q40_41_42.flow-meta.xml
=> BCMOHAD-16712-v1 || Updated the flow

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/X2nd_dose_will_be_adminstered_after_min__c.field-meta.xml
Removed 0 as default Value
Changed field **X2nd_dose_will_be_adminstered_after_min__c** default value from 0 to blank
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/X2nd_dose_will_be_adminstered_after_min__c.field-meta.xml
=> BCMOHAD-17893 || Removed 0 as default Value

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q40J__c.field-meta.xml
Updated the Formula of the field **ELG_Q40J__c**:
If field "If_yes_select_all_that_apply_1__c" contains "Other Condition / Co-morbidity" OR "Diabetes" OR "Frailty" OR Autoimune condition" OR "Chronic pain" OR Mental Disorder" then cell equals "1" OR if it does NOT contain "Other Condition / Co-morbidity", cell equals "2", OR (IF "None/Blank" cell equals "0")
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q40J__c.field-meta.xml
=> BCMOHAD-17894 || Updated Report Filed

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05A__c.field-meta.xml
Updated the Report field formula: IND_Q05A:
"If, yes Indigenous heritage" contains "First Nations" then cell is "1" OR, if No, then cell is "2" OR, if blank, cell is "0"
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05A__c.field-meta.xml
=> BCMOHAD-17896 || Updated the formula

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05B__c.field-meta.xml
Updated the Report field formula: IND_Q05B
"If, yes Indigenous heritage" contains "Métis", then cell is "1" OR, if No, then cell is "2" OR, if blank, cell is "0"
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05B__c.field-meta.xml
=> BCMOHAD-17897 || Updated the Report field formula: IND_Q05B

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05C__c.field-meta.xml
Updated the Report field formula: IND_Q05B
"If, yes Indigenous heritage" contains "Inuk/Inuik", then cell is "1" OR, if No, then cell is "2" OR, if blank, cell is "0"
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05C__c.field-meta.xml
=> Updated the Report field formula: IND_Q05C

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_assessment_period__c.field-meta.xml
Changed the Field display output for the field **Length_of_assessment_period__c**
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_assessment_period__c.field-meta.xml
=> BCMOHAD-18119 || Updated the formula

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q40J__c.field-meta.xml
Updated the formula for **ELG_Q40J__c**
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q40J__c.field-meta.xml
=> BCMOHAD-17894-v1 || Updated the formula

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05D__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05E__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05F__c.field-meta.xml
Updated the formula fields to show the response in Reports.
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05D__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05E__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05F__c.field-meta.xml
=> BCMOHAD-17900 || Updated the fields formula

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Record_ID1__c.field-meta.xml
Updated the formula to show the  Record_ID1__c properly
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Record_ID1__c.field-meta.xml
=> BCMOHAD-17902 || Updated the formula

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Record_ID1__c.field-meta.xml
Updated the formula and made some modifications to the existing formula
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Record_ID1__c.field-meta.xml
=> Corrected the existing Formula

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Missed_Issue_on_Form_1633__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Which_part_of_form_1633_was_missed__c.field-meta.xml
Updated the dependency field list with new values
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Missed_Issue_on_Form_1633__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Which_part_of_form_1633_was_missed__c.field-meta.xml
=> BCMOHAD-17903 || Updated the dependency field list

MAiD - Case Management App/force-app/main/default/flows/Status_update_prevention.flow-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/businessProcesses/MAiD Case.businessProcess-meta.xml, MAiD - Case Management App/force-app/main/default/standardValueSets/CaseStatus.standardValueSet-meta.xml
New picklist value added to the case status: Second Review. and flow update accordingly 
Flow rule: once the case is in “Second Review” status will be that can be updated to Ready for CC Review/Checks”, “CC/Review in Progress”, “Follow up required to Close”, but CANNOT be updated to “Awaiting forms” Follow up Required for CC Review/Checks” OR Closed  
Error notification message: This case can only be updated to Ready for CC Review/Checks, CC Review in Progress, or Follow up Required to close status 
Above requirements were met from the changes.
Fixes # (BCMOHAD-17983)
- [ X] New feature (non-breaking change which adds functionality)
1) New Picklist value added to the Case status picklist
2) the status updates related to the new flow are handled in the flow
List all …
=> BCMOHAD-17983- New picklist value and its related actions added

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Record_ID1__c.field-meta.xml
Updated the formula
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Record_ID1__c.field-meta.xml
=> BCMOHAD-17902 || Updated the changes

MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S1_2023_HC_Report_IV_and_IV_and_Oral.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S2_2023_HC_ReportOral_MAiD_P8M.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S6_2023_Health_CanadaIneligible_G9B.report-meta.xml
Added the New Report and rearranged the placement of fields in the reports 
MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S1_2023_HC_Report_IV_and_IV_and_Oral.report-meta.xml
MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S2_2023_HC_ReportOral_MAiD_P8M.report-meta.xml
MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml
MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S6_2023_Health_CanadaIneligible_G9B.report-meta.xml
MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
=> BCMOHAD-17901 || Reports Update

MAiD - Case Management App/force-app/main/default/objects/Account/fields/Specialty_2023Reg__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SPC_Q16__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SPC_S16__c.field-meta.xml
=> BCMOHAD-17925 SPC_Q16 and SPC_S16 Formulas Updated

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SPC_Q16__c.field-meta.xml
=> Bcmohad 17925 Special character Issue on the Picklist

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_S72G__c.field-meta.xml
ELG_S72G  formula changed
New formula: Form_1634__r.If_Other_specify_2__c
- [Yes ] Bug fix (non-breaking change which fixes an issue)
https://github.com/bcgov/MOH-MAiD/pull/682
=> ELG_S72G Formula field Updated

MAiD - Case Management App/force-app/main/default/lwc/icyCloseReferral/icyCloseReferral.js, MAiD - Case Management App/force-app/main/default/objects/Intake__c/listViews/ICY_All_Closed_Intakes.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/listViews/ICY_All_Open_Intakes.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/listViews/ICY_My_ICY_Intake.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/listViews/ICY_All_Closed_Referrals.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/listViews/ICY_All_Open_Referrals.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/listViews/ICY_My_Referrals.listView-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/Case.sharingRules-meta.xml
=> BCMOHAD-20385

MAiD - Case Management App/force-app/main/default/classes/ICY_IntegratedCarePlanCtrl.cls, MAiD - Case Management App/force-app/main/default/classes/ICY_IntegratedCarePlanCtrlTest.cls, MAiD - Case Management App/force-app/main/default/classes/ICY_SystemAccessRequestEmailTrigger_Test.cls, MAiD - Case Management App/force-app/main/default/classes/ICY_SystemAccessRequestEmailTrigger_Test.cls-meta.xml, MAiD - Case Management App/force-app/main/default/email/ICY_Email_Templates/ICY_Portal_Registration_Notification.email, MAiD - Case Management App/force-app/main/default/email/ICY_Email_Templates/ICY_Portal_Registration_Notification.email-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js, MAiD - Case Management App/force-app/main/default/lwc/icyIntegratedCarePlan/icyIntegratedCarePlan.html, MAiD - Case Management App/force-app/main/default/lwc/icyIntegratedCarePlan/icyIntegratedCarePlan.js, MAiD - Case Management App/force-app/main/default/objects/Case/listViews/ICY_All_Cases.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/Error_Log.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/ICY_Cannot_create_case_without_referral.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/fields/ICY_Assigned_To__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/listViews/ICY_My_Referrals.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/System_Access_Request__c/fields/Business_BCeID_IDIR__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/System_Access_Request__c/fields/ICY_Community_Assigned__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/System_Access_Request__c/recordTypes/ICY.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/pages/ICYSelfRegistration.page, MAiD - Case Management App/force-app/main/default/pages/IntegrateLogin.page, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Administrator_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Program_Leader_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MoH_Manage_Encryption_Keys.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/Referral__c.sharingRules-meta.xml, MAiD - Case Management App/force-app/main/default/triggers/ICY_SystemAccessRequestEmailTrigger.trigger, MAiD - Case Management App/force-app/main/default/triggers/ICY_SystemAccessRequestEmailTrigger.trigger-meta.xml
=> BCMOHAD-20479 - Various bug fixes.

MAiD - Case Management App/force-app/main/default/classes/ICY_CaseMember_Controller.cls, MAiD - Case Management App/force-app/main/default/classes/ICY_Notes_Documents_Controller.cls, MAiD - Case Management App/force-app/main/default/classes/YTS_Utility.cls, MAiD - Case Management App/force-app/main/default/lwc/iCY_NotesComponent/iCY_NotesComponent.html, MAiD - Case Management App/force-app/main/default/lwc/icyCaseTeamMembers/icyCaseTeamMembers.html, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.html, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.js, MAiD - Case Management App/force-app/main/default/objects/Case_Contact__c/validationRules/Cell_Phone_number_formatting.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case_Contact__c/validationRules/Missing_preferred_contact_info.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case_Contact__c/validationRules/Phone_number_formatting.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case_Contact__c/validationRules/Work_Phone_number_formatting.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/ICY_Notes__c/fields/Attendees__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/ICY_Notes__c/fields/Length_of_Meeting__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/validationRules/Time_traveller.validationRule-meta.xml
ICY Add Additional Fields and Validation for Referrals, Cases and Case Notes
Fixes # BCMOHAD-20838
- [] I have added tests that prove my fix is effective or that my feature works
=> BCMOHAD-20838

MAiD - Case Management App/force-app/main/default/classes/ICY_ReopenCaseCtrl.cls, MAiD - Case Management App/force-app/main/default/email/ICY_Email_Templates/ICY_Referral_Updated_Template.email, MAiD - Case Management App/force-app/main/default/email/ICY_Email_Templates/ICY_Referral_Updated_Template.email-meta.xml, MAiD - Case Management App/force-app/main/default/email/ICY_Email_Templates/Referral_Status_Closed_Template.email, MAiD - Case Management App/force-app/main/default/flows/ICY_Referral_Owner_Email_Flow.flow-meta.xml, MAiD - Case Management App/force-app/main/default/workflows/Referral__c.workflow-meta.xml
Submitted on behalf of @abusnita 
Fixes #20837
=> BCMOHAD-20837 - Outgoing email updates

MAiD - Case Management App/force-app/main/default/lwc/icyIntegratedCarePlan/icyIntegratedCarePlan.js
As per email discussion, adds edit capability to goals on the Integrated Care Plan. Agreement is if the user can view the record, they can edit the goals.
=> Integrated Care Plan "goal edit" fix.

MAiD - Case Management App/force-app/main/default/permissionsetgroups/MAiD_Manager_1_Group.permissionsetgroup-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/Account.sharingRules-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/Case.sharingRules-meta.xml
Fixes # (BCMOHAD-20478)
- [ Yes] Bug fix (non-breaking change which fixes an issue)
1) MAiD Manager1 PermissionSet Group Updated
2) MAiD manager Permission Set Updated
https://github.com/bcgov/MOH-MAiD/pull/687
=> BCMOHAD-20478

MAiD - Case Management App/force-app/main/default/objects/Case_Contact__c/validationRules/Cell_Phone_number_formatting.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case_Contact__c/validationRules/Missing_preferred_contact_info.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case_Contact__c/validationRules/Phone_number_formatting.validationRule-meta.xml
Deactivating Validation Rules
Fixes # BCMOHAD-20838
=> BCMOHAD-20838-1 - Deactivating Validation Rules

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
Add MAiD access to Type Field
Fixes #  BCMOHAD-21222
=> BCMOHAD-21222 - Add MAiD access to Type Field

MAiD - Case Management App/force-app/main/default/classes/YTS_Utility.cls
formatting date time added when adding Team member on Referrals and case
Fixes # BCMOHAD-21426
=> BCMOHAD-21426 - formatting date time

MAiD - Case Management App/force-app/main/default/classes/ContributionSharingController.cls, MAiD - Case Management App/force-app/main/default/classes/ICYSelfRegistrationController.cls, MAiD - Case Management App/force-app/main/default/labels/CustomLabels.labels-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/iCY_NotesComponent/iCY_NotesComponent.js, MAiD - Case Management App/force-app/main/default/lwc/icyCaseTeamMembers/icyCaseTeamMembers.js, MAiD - Case Management App/force-app/main/default/lwc/icyCloseReferral/icyCloseReferral.js, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditCaseTeamMember/icyCreateEditCaseTeamMember.js, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditDocument/icyCreateEditDocument.js, MAiD - Case Management App/force-app/main/default/lwc/icyCreateInTakeRecord/icyCreateInTakeRecord.js, MAiD - Case Management App/force-app/main/default/lwc/icyCustomLookupComponent/icyCustomLookupComponent.html, MAiD - Case Management App/force-app/main/default/lwc/icyDocumentsComponent/icyDocumentsComponent.js, MAiD - Case Management App/force-app/main/default/lwc/icyIntegratedCarePlan/icyIntegratedCarePlan.js, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js, MAiD - Case Management App/force-app/main/default/lwc/icyNotes/icyNotes.js, MAiD - Case Management App/force-app/main/default/lwc/icyPlansAddHavesAndNeeds/icyPlansAddHavesAndNeeds.js, MAiD - Case Management App/force-app/main/default/lwc/icyReopenCase/icyReopenCase.js, MAiD - Case Management App/force-app/main/default/lwc/ytsCasePrintPlan/ytsCasePrintPlan.js, MAiD - Case Management App/force-app/main/default/lwc/ytsCreateEditReferralContact/ytsCreateEditReferralContact.js
Error message cleanup tasks
Fixes # BCMOHAD-21365
=> BCMOHAD-21365 - Error message cleanup

MAiD - Case Management App/force-app/main/default/objects/Referral__c/validationRules/Phone_number_Validation.validationRule-meta.xml
Referral-Phone number Validation
Fixes # BCMOHAD-21360
- [X ] My code follows the style guidelines of this project
=> BCMOHAD-21360 - Referral-Phone number Validation

MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html
BCMOHAD-21360 - LWC adding  min length = 10 to force full entry of phone #
- [x ] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the style guidelines of this project
=> BCMOHAD-21360 - LWC min length

MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/Copy_of_ICY_Evaluation_Data_Referrals_9pL.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/Copy_of_ICY_Reason_for_case_closed_COM_4xW.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/Copy_of_ICY_Touch_points_with_youth_MA_mZ5.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/Copy_of_ICY_Touch_points_with_youth_MA_vu0.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Evaluation_Data_ReferralsCoastMoun_Bf2.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Evaluation_Data_ReferralsR_SSU.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Evaluation_Data_ReferralsRichmond_qB9.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Evaluation_Data_Referrals_N3I.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Reason_9MF.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Reason_for_case_closed_COMOX_JhS.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Reason_for_case_closed_MAPLE_Ze6.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Reason_for_case_closed_OKANAGAN_teH.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Touch_points_with_youth_3HR.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Touch_points_with_youth_CO_L7b.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Touch_points_with_youth_OKANAGAN_0uf.report-meta.xml
Adding Referral To To Evaluation Reports 
Adding Case Closed Reason to ICY Reason for case Closed Reports 
Adding Team member to ICY touch points Report
- [X ] New feature (non-breaking change which adds functionality)
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
=> Bcmohad 20917 1

MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/Copy_of_ICY_Touch_points_with_youth_MA_mZ5.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/Copy_of_ICY_Touch_points_with_youth_MA_vu0.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Case_with_Integrated_Care_Plan_COA_gjX.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Case_with_Integrated_Care_Plan_COM_KxB.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Case_with_Integrated_Care_Plan_M2C.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Case_with_Integrated_Care_Plan_OKA_oe9.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Case_with_Integrated_Care_Plan_RIC_Eax.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Touch_points_with_youth_3HR.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Touch_points_with_youth_CO_L7b.report-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYMMHAReports/ICY_Touch_points_with_youth_OKANAGAN_0uf.report-meta.xml
Update ICY Case with integrated Care Plan to only pulls the active domains
Fixes # Bcmohad-20917
=> Bcmohad-20917-2  - Update ICY Case with integrated Care Plan

MAiD - Case Management App/force-app/main/default/reports/ICYDashboardReports/ICY_Inactive_Case_Report_tML.report-meta.xml
BCMOHAD-20833-2 - Changes to Inactive cases report done In prod and need to be merged for next release
Fixes # (BCMOHAD-20833)
=> BCMOHAD-20833-2 - Changes to Inactive cases report

MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js, MAiD - Case Management App/force-app/main/default/lwc/icyPlansAddHavesAndNeeds/icyPlansAddHavesAndNeeds.js, MAiD - Case Management App/force-app/main/default/quickActions/Intake__c.ICY_Close_Intake.quickAction-meta.xml
Updating Error messages
Fixes # (BCMOHAD-21365)
=> BCMOHAD-21365-1 Updating Error messages

MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js
BCMOHAD-21367- Default Document Type
Fixes # (BCMOHAD-21367)
=> BCMOHAD-21367- Default Document Type

MAiD - Case Management App/force-app/main/default/classes/ICY_CustomSettingsController.cls, MAiD - Case Management App/force-app/main/default/classes/ICY_CustomSettingsController.cls-meta.xml, MAiD - Case Management App/force-app/main/default/flexipages/ICY_Cases_Record_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/flexipages/ICY_Home_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/flexipages/ICY_Intake_Record_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/flexipages/ICY_Referral_Record_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/flowDefinitions/Update_Privacy_Acknowledgement.flowDefinition-meta.xml, MAiD - Case Management App/force-app/main/default/flows/Update_Privacy_Acknowledgement.flow-meta.xml, MAiD - Case Management App/force-app/main/default/labels/CustomLabels.labels-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyAlertBannerOutage/icyAlertBannerOutage.html, MAiD - Case Management App/force-app/main/default/lwc/icyAlertBannerOutage/icyAlertBannerOutage.js, MAiD - Case Management App/force-app/main/default/lwc/icyAlertBannerOutage/icyAlertBannerOutage.js-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyAlertBannerPrivacyAgreement/icyAlertBannerPrivacyAgreement.html, MAiD - Case Management App/force-app/main/default/lwc/icyAlertBannerPrivacyAgreement/icyAlertBannerPrivacyAgreement.js, MAiD - Case Management App/force-app/main/default/lwc/icyAlertBannerPrivacyAgreement/icyAlertBannerPrivacyAgreement.js-meta.xml, MAiD - Case Management App/force-app/main/default/objects/ICY_Outage_Message_Settings__c/ICY_Outage_Message_Settings__c.object-meta.xml, MAiD - Case Management App/force-app/main/default/objects/ICY_Outage_Message_Settings__c/fields/Outage_Message__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/ICY_Outage_Message_Settings__c/fields/Outage__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/User/fields/Privacy_Acknowledgement__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/User/fields/Privacy_Statement_Accepted__c.field-meta.xml
Adding Agreement banner and outage Banner
Fixes # (BCMOHAD-21374)
=> BCMOHAD-21374 - Adding Agreement banner and outage Banner

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
Updated the field permissions for MAiD Analysts permission set.
=> BCMOHAD-22022 || Updated the field permissions

MAiD - Case Management App/force-app/main/default/lwc/icyIntegratedCarePlan/icyIntegratedCarePlan.html
BCMOHAD-21368- Adding info icon
Fixes # (BCMOHAD-21368)
=> BCMOHAD-21368- Adding info icon

MAiD - Case Management App/.forceignore, MAiD - Case Management App/force-app/main/default/entitlementProcesses/maid entitlement process_v3.entitlementProcess-meta.xml
Updated the Milestone time from 6 days to 8 days.
Commented the Entitlement Processes in .forceignore
MAiD - Case Management App/.forceignore
MAiD - Case Management App/force-app/main/default/entitlementProcesses/maid entitlement process_v3.entitlementProcess-meta.xml
=> BCMOHAD-20701 || Changed from 6 to 8 days

MAiD - Case Management App/force-app/main/default/flowDefinitions/Update_Privacy_Acknowledgement.flowDefinition-meta.xml, MAiD - Case Management App/force-app/main/default/labels/CustomLabels.labels-meta.xml
Adding Custom Labels - updating Flow Definition to resolve Packaging erros 
Fixes # (21365 ,BCMOHAD-21374)
=> BCMOHAD-21365-2 - Updating Custom Labels and Flow Definition

MAiD - Case Management App/force-app/main/default/flowDefinitions/Update_Privacy_Acknowledgement.flowDefinition-meta.xml
Remove Flow Definition
Fixes # (BCMOHAD-21365)
=> BCMOHAD-21365 Remove Flow Definition

MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.html, MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js
BCMOHAD-21367 -  document type required
Fixes # (BCMOHAD-21367)
=> BCMOHAD-21367 -  document type required

MAiD - Case Management App/force-app/main/default/classes/ICY_CaseMember_Controller.cls, MAiD - Case Management App/force-app/main/default/labels/CustomLabels.labels-meta.xml
BCMOHAD-21366 Allowing multiple Supplemental Team member added for Case and Referral
Fixes # (BCMOHAD-21366)
=> BCMOHAD-21366 - Allowing multiple Supplemental Team member

MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js
BCMOHAD-21367-2 update Enabling disabling Buttons
Fixes # (BCMOHAD-21367)
=> BCMOHAD-21367-2 update Enabling disabling Buttons

MAiD - Case Management App/force-app/main/default/classes/ICY_CaseMember_Controller.cls, MAiD - Case Management App/force-app/main/default/classes/ICY_SystemAccessRequestEmailTrigger_Test.cls, MAiD - Case Management App/force-app/main/default/email/ICY_Email_Templates/ICY_Portal_Registration_Notification.email, MAiD - Case Management App/force-app/main/default/lwc/icyCaseTeamMembers/icyCaseTeamMembers.html, MAiD - Case Management App/force-app/main/default/objects/System_Access_Request__c/fields/Profession_Role__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/pages/ICYSelfRegistration.page, MAiD - Case Management App/force-app/main/default/profiles/ICYTest Profile.profile-meta.xml
BCMOHAD-21370 Case Team Members – Show More Information
Fixes # (BCMOHAD-21370)
=> Bcmohad 21370 1

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_assessment_period__c.field-meta.xml
Updated the Length of assessment field formula in form 1634
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_assessment_period__c.field-meta.xml
=> BCMOHAD-22268 || Updated the Length of assessment formula

MAiD - Case Management App/force-app/main/default/flows/MAiD_Case_Stage_Changes_AFTER.flow-meta.xml
Updated the Milestone from 6 days to 8 days
MAiD - Case Management App/force-app/main/default/flows/MAiD_Case_Stage_Changes_AFTER.flow-meta.xml
=> BCMOHAD-22438 || Updated from 6 to 8 days

MAiD - Case Management App/force-app/main/default/flows/Status_5_update_flow.flow-meta.xml
Updated the MAiD Analyst case closing condition
MAiD - Case Management App/force-app/main/default/flows/Status_5_update_flow.flow-meta.xml
=> BCMOHAD-22252 || Updated the MAiD Analyst Closure condition

MAiD - Case Management App/force-app/main/default/objects/Case/fields/MAiD_Reporting_Deadline__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Pharmacy_Reporting_Deadline__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reporting_Status__c.field-meta.xml
Created the new formula fields on the case object.
MAiD - Case Management App/force-app/main/default/objects/Case/fields/MAiD_Reporting_Deadline__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Pharmacy_Reporting_Deadline__c.field-meta.xml
=> BCMOHAD-22274 || Created new formula fields

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reporting_Status__c.field-meta.xml
Updated the Reporting status field formula
=> BCMOHAD-22274 || Updated the Reporting status field 

MAiD - Case Management App/.forceignore, MAiD - Case Management App/.sf/config.json, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
=> BCMOHAD-22811 || Permission sets

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Racial_Ethinic_or_Cultural_Group__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1632__c/fields/Requestor_initiated_Safeguards__c.field-meta.xml
Updated the field label names in case and Form 1632 objects.
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Racial_Ethinic_or_Cultural_Group__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Form_1632__c/fields/Requestor_initiated_Safeguards__c.field-meta.xml
=> BCMOHAD-22662 || Updated the Field Label Names

MAiD - Case Management App/force-app/main/default/flows/Status_5_update_flow.flow-meta.xml
Updated the status feedback error message for BCCS manager review and also moved the locations of the flow elements for the visibility purpose
MAiD - Case Management App/force-app/main/default/flows/Status_5_update_flow.flow-meta.xml
=> BCMOHAD-22267 || Updated the BCCS Error message

MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Case_Creation_Status_Check.validationRule-meta.xml
Created a validation rule to prevent the change of a case status (Awaiting forms, Follow-up Required for CC Review Checks, Ready for CC Review) while creating a case
MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Case_Creation_Status_Check.validationRule-meta.xml
=> BCMOHAD-22296 || Case Creation Status

MAiD - Case Management App/force-app/main/default/sharingRules/ICY_Document__c.sharingRules-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/ICY_Notes__c.sharingRules-meta.xml
BCMOHAD-22887 - Switching Sharing Rules to Read Write for ICY Documents and Notes 
Fixes # (BCMOHAD-22887)
=> BCMOHAD-22887 - Switching Sharing Rules to Read Write

MAiD - Case Management App/force-app/main/default/objects/Referral__c/listViews/ICY_All_Open_Referrals.listView-meta.xml
BCMOHAD-22916 - Removing Ready for Intake
Fixes # (BCMOHAD-22916)
=> BCMOHAD-22916 - Removing Ready for Intake

MAiD - Case Management App/force-app/main/default/flows/Status_5_update_flow.flow-meta.xml
Updated the Status Message in the flow
MAiD - Case Management App/force-app/main/default/flows/Status_5_update_flow.flow-meta.xml
=> BCMOHAD-22267 || Updated Manager status message

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reporting_Status__c.field-meta.xml
Updated the Case Page layout and updated the reporting status field formula
=> BCMOHAD-22274 || Updated the Page layout and formula field

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reporting_Status__c.field-meta.xml
Updated the formula field in the case object
=> BCMOHAD-22274 || Updated the condition

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reporting_Status__c.field-meta.xml
Updated the formula with the conditions and corrected the name
=> BCMOHAD-22274 || Updated the condition and corrected spelling

MAiD - Case Management App/force-app/main/default/objects/Case/listViews/ICY_All_Closed_Cases.listView-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/listViews/ICY_All_Closed_Intakes.listView-meta.xml
=> List View Updated

MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
BCMOHAD-23418
- [Yes ] Bug fix (non-breaking change which fixes an issue)
=> BCMOHAD-23418

MAiD - Case Management App/force-app/main/default/classes/ICYNotesTriggerHandler.cls
BCMOHAD-23038-1 - Fix Critical incident notification
Fixes # BCMOHAD-23038 
=> BCMOHAD-23038-1 - Fix Critical incident notification

MAiD - Case Management App/.forceignore, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Administrator_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Program_Leader_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/User.sharingRules-meta.xml
Updated the Permission sets and created a new sharing rule for User object.
**Post-deployment step:**
Goto setup, type Sharing setting in the quickfind box, select the sharing settings and change the user object settings to private.
--> Removed viewAll Users permissions and gave view roles permissions
--> Created new User sharing rule
--> Commented the Sharing rules in .forceignore so that we can retireve the sharing rules.
MAiD - Case Management App/.forceignore
MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Administrator_Permissions.permissionset-meta.xml
MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Program_Leader_ …
=> BCMOHAD-23294 || Updated the Permission set

MAiD - Case Management App/force-app/main/default/classes/ICYNotesTriggerHandler.cls
BCMOHAD-23038-2 Reverting Critical Incident
Fixes # (BCMOHAD-23038-)
=> BCMOHAD-23038-2 Reverting Critical Incident

MAiD - Case Management App/force-app/main/default/reports/ICYSharedIndicatorsReports/CY_being_seen_1_Members_fzC.report-meta.xml
BCMOHAD-23569 - Adding user fields on reports 
Fixes # (BCMOHAD-23569)
=> BCMOHAD-23569 - Adding user fields on reports

MAiD - Case Management App/force-app/main/default/sharingRules/User.sharingRules-meta.xml
Updated the User Sharing rule for MAiD Users.
Note: By this All MAiD Users can see All MAiD Users.
=> BCMOHAD-23294 || Updated the Sharing Rules

MAiD - Case Management App/force-app/main/default/classes/ICY_CompleteIntakeCtrl.cls
Updated the class from public to public without sharing
Updated the insert to db.insert 
MAiD - Case Management App/force-app/main/default/classes/ICY_CompleteIntakeCtrl.cls
=> BCMOHAD-23342 || Updated the Insert to DB.Insert

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
=> Permission set update

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Pharmacy_Reporting_Status__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reporting_Status__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
Created a new field
Renamed an existing field
Updated the page layout field alignment
Updated the permission set with the new field permissions
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Pharmacy_Reporting_Status__c.field-meta.xml
=> BCMOHAD-23711 || Created new reporting status field

MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls
Updated the apex class to make sure that the duplicate rule checks in.
Note: Kept the commented code because we need it for another upcoming ticket.
Test class will be updated in the coming ticket.
MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls
=> BCMOHAD-23370 || Updated the apex class

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Pharmacy_Reporting_Status__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reporting_Status__c.field-meta.xml
Updated the formula fields with Not Applicable status
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Pharmacy_Reporting_Status__c.field-meta.xml
=> BCMOHAD-23859 || Updated the formula fields

MAiD - Case Management App/force-app/main/default/flows/ICY_Referral_Owner_Assignment_Flow.flow-meta.xml, MAiD - Case Management App/force-app/main/default/groups/ICY_Central_Coast_CL_NCL.group-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/ICY_Geographic_Area__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/ICY_Close_Case.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/ICY_Standard_Case.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Geographic_Area__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General_Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical_Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/System_Access_Request__c/fields/ICY_Community_Assigned__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/System_Access_Request__c/recordTypes/ICY.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/queues/ICY_Central_Coast.queue-meta.xml, MAiD - Case Management App/force-app/main/default/roles/Central_Coast_Team_Admin.role-meta.xml, MAiD - Case Management App/force-app/main/default/roles/Central_Coast_Team_Clinical_Member.role-meta.xml, MAiD - Case Management App/force-app/main/default/roles/Central_Coast_Team_Non_Clinical_Member.role-meta.xml, MAiD - Case Management App/force-app/main/default/roles/Central_Coast_Team_Program_Leader.role-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/Case.sharingRules-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/Referral__c.sharingRules-meta.xml
BCMOHAD-23754 - Adding Central Coast
Fixes # (BCMOHAD-23754)
MANUAL STEPS:
=================
Add to Groups:
ICY_Central_Coast_CL_NCL 2 Roles :
Central Coast Team Clinical Member
Central Coast Team Non Clinical Member
All_ICY_Admins Role:
Central Coast Team Admin
All_ICY_Clinical_Non_Clinical   Role:
Central Coast Team Clinical Member
Central Coast Team Non Clinical Member
All_ICY_Program_Leaders  Role:
Central Coast Team Program Leader
ICY_Restiricted_Data  Role:
Central Coast Team Admin
Central Coast Team Clinical Member
Central Coast Team Program Leader
=> BCMOHAD-23754 - Adding Central Coast

MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
=> RUN Flow Permission in Permission sets

MAiD - Case Management App/force-app/main/default/classes/ICYNotesTriggerHandler.cls
BCMOHAD-23865 - Updating Notification logic
Fixes # (BCMOHAD-23865)
=> BCMOHAD-23865 - Updating Notification logic

MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls
Updated the Apex class class with the spelling correction and added try catch
MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls
=> BCMOHAD-23370 || Updated the Apex class with try catch

MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Current_Age__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Current_Supports__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Rationale_For_Closure__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Primary_Contact_Is_Individual__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Sub_Status__c.field-meta.xml
BCMOHAD-24095-2 updating help text and description
Fixes # (BCMOHAD-24095)
=> BCMOHAD-24095-2 updating help text and description

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/PROC_Q75_Formula__c.field-meta.xml
Updated the Formula field
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/PROC_Q75_Formula__c.field-meta.xml
=> BCMOHAD-24203|| Updated the formula field

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Preferred_Gender__c.field-meta.xml
Updated the Label Name of the field
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Preferred_Gender__c.field-meta.xml
=> BCMOHAD-24542 || Updated the label name

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Requestor_disability_opinion__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Requestor_disability_opinion__c.field-meta.xml
=> BCMOHAD-24546 || Updated the Picklist Values

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Usual_Place_of_Residence__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Usual_Place_of_Residence__c.field-meta.xml
=> BCMOHAD-24547 || Added new Picklist values

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Length_of_Disability__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Length_of_Disability__c.field-meta.xml
=> BCMOHAD-24574 || Updated the new picklist values

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Daily_Activity_Limits__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Daily_Activity_Limits__c.field-meta.xml
=> BCMOHAD-24575 || Added the new picklist value

MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Private_Residence_Living_arrangement__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Private_Residence_Living_arrangement__c.field-meta.xml.
=> BCMOHAD-24576 || Added the new picklist value

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Racial_Ethinic_or_Cultural_Group__c.field-meta.xml
Updated the picklist values of the field
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Racial_Ethinic_or_Cultural_Group__c.field-meta.xml
=> BCMOHAD-24545 || Updated the Picklist values

MAiD - Case Management App/force-app/main/default/classes/YTS_Utility.cls, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditCaseTeamMember/icyCreateEditCaseTeamMember.js
BCMOHAD-24528 Adding validation to check if user or contact has been captured prior of saving /adding team member
Fixes # (BCMOHAD-24528)
=> Bcmohad 24528

MAiD - Case Management App/force-app/main/default/objects/Intake__c/recordTypes/ICY_Intake_Read_Only.recordType-meta.xml
BCMOHAD-24532 Assigning Proper compact layout
Fixes # (BCMOHAD-24532 )
=> BCMOHAD-24532 Assigning Proper compact layout

MAiD - Case Management App/force-app/main/default/objects/Account/fields/Specialty_2023Reg__c.field-meta.xml
Added the new helptext to the field
MAiD - Case Management App/force-app/main/default/objects/Account/fields/Specialty_2023Reg__c.field-meta.xml
=> BCMOHAD-24583 || Added the help text

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Preferred_Gender__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Preferred_Gender__c.field-meta.xml
=> BCMOHAD-24543 || Added the new picklist values

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Identify_as_Indigenious__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Identify_as_Indigenious__c.field-meta.xml
=> BCMOHAD-24544 || Added the new picklist values

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_medical_condition__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_medical_condition__c.field-meta.xml
=> BCMOHAD-24579 || Added the new picklist values

MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Patient_required_palliative_care__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Patient_required_palliative_care__c.field-meta.xml
=> BCMOHAD-24578 || Added the new picklist values

MAiD - Case Management App/force-app/main/default/objects/Case/fields/Older_MAiD_Forms_to_2021__c.field-meta.xml
Updated the label Name and Added the Help Text
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Older_MAiD_Forms_to_2021__c.field-meta.xml
=> BCMOHAD-24540 || Updated the label Name and Added the Help Text

MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Private_Residence_Living_arrangement__c.field-meta.xml
=> BCMOHAD-24576- New Picklist Value added

MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/MAiD_Case.recordType-meta.xml
https://github.com/bcgov/MOH-MAiD/pull/796
=> BCMOHAD-24576

MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditCaseTeamMember/icyCreateEditCaseTeamMember.js
BCMOHAD-24528 Correction to Addmyself functionality
Fixes # (BCMOHAD-24528 )
=> BCMOHAD-24528 Correction to Addmyself functionality

MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Case__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Age_At_Referral__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Referral_Type__c.field-meta.xml
BCMOHAD-24095-3 - Update Help text
Fixes # (BCMOHAD-24095)
=> BCMOHAD-24095-3 - Update Help text

MAiD - Case Management App/force-app/main/default/classes/ICYNotesTriggerHandler.cls
BCMOHAD-24738 Sending notification to PL admin and team members
Fixes # (BCMOHAD-24738)
=> BCMOHAD-24738 Sending notification to PL admin and team members

MAiD - Case Management App/force-app/main/default/classes/ICYNotesTriggerHandler.cls
Reverting PR-799 since the functionality is not working as intended
=> Revert "BCMOHAD-24738 Sending notification to PL admin and team members"

MAiD - Case Management App/force-app/main/default/classes/ICY_CaseMember_Controller.cls
BCMOHAD-24854 - Updating Accountshare logic
Fixes # (BCMOHAD-24854)
=> BCMOHAD-24854 - Updating Accountshare logic

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
Updated Permission Set 
Updated Page Layout for Case
=> BCMOHAD-24539 || Update PS and Layout for Case

MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/MAiD_Case.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SEX_Q06__c.field-meta.xml
Updated the formula field and updated the case recordtype with the new picklist vales 
MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/MAiD_Case.recordType-meta.xml
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SEX_Q06__c.field-meta.xml
=> BCMOHAD-24607 || Updated the formula field

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RFD_Q05__c.field-meta.xml
HC Template formula update RFD_Q05
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RFD_Q05__c.field-meta.xml
=> Bcmohad 24606 || formula update RFD_Q05

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05D__c.field-meta.xml
Updated the formula for the field
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05D__c.field-meta.xml
=> BCMOHAD-24612 || Updated the field formula

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05E__c.field-meta.xml
Updated the formula for the filed
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05E__c.field-meta.xml
=> BCMOHAD-24613 || Updated the formula

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q25__c.field-meta.xml
update formula field DIS_Q25
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q25__c.field-meta.xml
=> BCMOHAD-25000 || update DIS_Q25

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q30__c.field-meta.xml
update formula DIS_Q30
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q30__c.field-meta.xml
=> Bcmohad 25002 || update formula DIS_Q30

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/REQ_Q20__c.field-meta.xml
Update formula field REQ_Q20__c to text 
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/REQ_Q20__c.field-meta.xml
=> BCMOHAD-24749 Update formula REQ_Q20

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/validationRules/Rule_42_Data_Check.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/Maid_Validation_Settings__c.object-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/fields/Case_Type_Reported_Date__c.field-meta.xml
Reverting the changes from dev branch since the Flow is not working as intended.
=> Revert "BCMOHAD-24595 || Update flow "

MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js
Bcmohad 24793 Update logic to prevent creating empty cases when error occurs during the process of intake completion .
Fixes # (Bcmohad 24793)
=> Bcmohad 24793

MAiD - Case Management App/force-app/main/default/classes/ICYNotesTriggerHandler.cls
Sending notifcation to PL Admin and team members
As a user,
I want to change the recipients for the email sent when critical incident on case is logged
so that PL , admin and all the assigned teams members gets the email notification 
Updated the apex class to incorporate the changes.
ICYNotesTriggerHandler
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any …
=> Update ICYNotesTriggerHandler for MOHAD-24738

MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js
Reverts PR #821 from Release 222  branch since the changes are not working as intended 
ISBINC0011671 - ICY - Integrate (Salesforce): Unable to create record - empty records
=> Revert "Bcmohad 24793"

MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Cannot_change_Status_Closed_CL_NCL.validationRule-meta.xml
Bcmohad 25033  Preventing CL NCL from reopening cases
Fixes # (Bcmohad 25033)
=> Bcmohad 25033  Preventing CL NCL from reopening cases

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q15__c.field-meta.xml
Update formula field DIS_Q15
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q15__c.field-meta.xml
=> BCMOHAD-25020 || Update formula field DIS_Q15

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/PROC_Q185C__c.field-meta.xml
Updated the formula field as per the client requirement.
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/PROC_Q185C__c.field-meta.xml
=> BCMOHAD-24814 || Updated the formula

MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js
BCMOHAD-24793-1 Update postal code Validation
Fixes # (BCMOHAD-24793)
=> BCMOHAD-24793-1 Update postal code Validation

MAiD - Case Management App/force-app/main/default/flows/Status_update_prevention.flow-meta.xml
Updated the MAiD Assessment of eligibility status criteria.
case status to be moved from Awaiting Forms to Closed if case type is "MAiD Assessment of Eligibility
so that case status can be directly moved to closed status 
MAiD - Case Management App/force-app/main/default/flows/Status_update_prevention.flow-meta.xml
=> BCMOHAD-24605 || updated the Assessment of eligibility

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Bcmohad 24598 Update Rule 25 I want Validation rule 25 to be implemented
so that Patient received palliative care? field cannot be left blank if Validation rule 25 criteria is fulfilled
Fixes # (Bcmohad 24598)
=> BCMOHAD-24598-1 - Update Rule 25

MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/Returning_Prescriber_Name__c.field-meta.xml
update lookup filter on field ReturningPrescriberName
MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/Returning_Prescriber_Name__c.field-meta.xml
=> BCMOHAD-24840 || update lookup filter on ReturningPrescriberName

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RAC_Q05I__c.field-meta.xml
Updated the formula field Data type and updated the formula
IF field "Racial, Ethinic or Cultural Group" contains "Do not know" then cell equals "1"
OR if it does NOT contain "Do not know" then cell equals "2"
OR if blank cell is "0"
OR if "No Data Disclosed" then cell equals "No Data Disclosed"
OR if "Pre-2023 MAiD Request-No data available" cell is "Pre-2023 MAiD Request-No data available" 
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RAC_Q05I__c.field-meta.xml
=> BCMOHAD-24619 || Updated the formula field type

MAiD - Case Management App/force-app/main/default/labels/CustomLabels.labels-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js
BCMOHAD-25104 Update Handling Error
Fixes # (BCMOHAD-25104)
- [ X] Any dependent changes have been merged and published in downstream modules
=> BCMOHAD-25104 - Update Handling Error

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05F__c.field-meta.xml
Updated the formula for IND_Q05F
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05F__c.field-meta.xml
=> BCMOHAD-24617 || Updated the formula

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q05__c.field-meta.xml
Updated the formula field RES_Q05
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q05__c.field-meta.xml
=> BCMOHAD-24748 || Updated the formula field RES_Q05

MAiD - Case Management App/force-app/main/default/layouts/Form_1641__c-Form 1641 Layout.layout-meta.xml
Updated the Form 1641 Pagelayout
MAiD - Case Management App/force-app/main/default/layouts/Form_1641__c-Form 1641 Layout.layout-meta.xml
=> BCMOHAD-24581 || Updated the page layout

MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Other_Preferred_Gender_Specify__c.field-meta.xml
Update label for field If_Other_Preferred_Gender_Specify__c
MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Other_Preferred_Gender_Specify__c.field-meta.xml
=> BCMOHAD-25154 ||Update label for field

MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls
Update Apex Class getCasePHNandUpdate
MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls
=> BCMOHAD-24537 || Update Apex Class getCasePHNandUpdate

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Update flow mandatory data rule 42 and 46
Post Deployment Steps :  Setup -> Navigate to flows -> Mandatory Data -> Activate the modified version 
MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
=> BCMOHAD-24595-2 || Update flow mandatory data rule 42 and 46

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q05__c.field-meta.xml
Updated the RES_Q05 picklist values Pre-2023 MAiD Request-No data
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q05__c.field-meta.xml
=> BCMOHAD-24748-V1|| Updated the Picklist value

MAiD - Case Management App/force-app/main/default/layouts/Form_1641__c-Form 1641 Layout.layout-meta.xml
Updated the Pagelayout of form 1641
MAiD - Case Management App/force-app/main/default/layouts/Form_1641__c-Form 1641 Layout.layout-meta.xml
=> BCMOHAD-24581-V1 || Updated the 1641 Page layout

MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
BCMOHAD-24598-2- Update Rule 25 Message
Fixes # (BCMOHAD-24598)
=> BCMOHAD-24598-2- Update Rule 25 Message

MAiD - Case Management App/force-app/main/default/labels/CustomLabels.labels-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/validationRules/Postal_Code_Validation.validationRule-meta.xml
Bcmohad 25104 1 Add validation Rule 
Fixes # (25104 )
=> Bcmohad 25104 1 Add validation Rule 

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RAC_Q05I__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q05__c.field-meta.xml
Updated the RAC_Q05I value "Pre-2023 MAiD Request-No data"
RES_Q05 value with Pre 2023 MAiD Request - No data
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RAC_Q05I__c.field-meta.xml
=> BCMOHAD-24619-V1 || Updated the picklist value

MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Was_Education_Provided_And_Lvl_Selected.validationRule-meta.xml
Create new Validation Rule for Education Provided
MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Was_Education_Provided_And_Lvl_Selected.validationRule-meta.xml
=> BCMOHAD-24585_1 || Create new Validation Rule for Education Provided

MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_yes_specify__c.field-meta.xml
Update Help Text
MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_yes_specify__c.field-meta.xml
=> BCMOHAD-25305 || Update Help Text

MAiD - Case Management App/force-app/main/default/flexipages/ICY_Intake_Record_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/flexipages/ICY_Referral_Record_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/flows/ICY_Intake_Reopen_Flow.flow-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Intake__c-ICY Intake Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-Read-Only.layout-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyReferralRecordInfo/icyReferralRecordInfo.html, MAiD - Case Management App/force-app/main/default/lwc/icyReopenIntake/icyReopenIntake.html, MAiD - Case Management App/force-app/main/default/lwc/icyReopenIntake/icyReopenIntake.js, MAiD - Case Management App/force-app/main/default/lwc/icyReopenIntake/icyReopenIntake.js-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyReopenReferral/icyReopenReferral.html, MAiD - Case Management App/force-app/main/default/lwc/icyReopenReferral/icyReopenReferral.js, MAiD - Case Management App/force-app/main/default/lwc/icyReopenReferral/icyReopenReferral.js-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/fields/Closed_Reason__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/fields/ICY_Reopened_Date__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Reopened_Date__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/quickActions/Intake__c.ICY_Reopen_Intake.quickAction-meta.xml, MAiD - Case Management App/force-app/main/default/quickActions/Referral__c.ICY_Reopen_Referral.quickAction-meta.xml
BCMOHAD-25665  ICY - Allow users to reopen the referrals and intake
Fixes # (BCMOHAD-25665)
=> BCMOHAD-25665  ICY - Allow users to reopen the referrals and intake

MAiD - Case Management App/force-app/main/default/flexipages/ICY_Intake_Record_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Intake__c-ICY Intake Layout.layout-meta.xml
BCMOHAD-25665-1 - Adding Related list Intake History
Fixes # (BCMOHAD-25665)
=> BCMOHAD-25665-1 - Adding Related list Intake History

MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Referral_Source__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General_Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical_Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/Read_Only.recordType-meta.xml
BCMOHAD-25678 - Make Referral source Required
Fixes # (BCMOHAD-25678)
=> BCMOHAD-25678 - Make Referral source Required

MAiD - Case Management App/force-app/main/default/objects/Intake__c/fields/ICY_Closed_By__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/fields/ICY_Who_Is_Doing__c.field-meta.xml
BCMOHAD-25665-2 - Adding track history
Fixes # (BCMOHAD-25665)
=> BCMOHAD-25665-2 - Adding track history

MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-Read-Only.layout-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyCloseReferral/icyCloseReferral.js, MAiD - Case Management App/force-app/main/default/lwc/icyReferralRecordInfo/icyReferralRecordInfo.html, MAiD - Case Management App/force-app/main/default/lwc/icyReopenReferral/icyReopenReferral.js, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Closed_Date__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYSharedIndicatorsReports/d_ICY_Closed_Referral_Last_Month_dfd.report-meta.xml
BCMOHAD-25679 - Adding new field Referral Closed date
Fixes # (BCMOHAD-25679)
=> BCMOHAD-25679 - Adding new field Referral Closed date

MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-Read-Only.layout-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js, MAiD - Case Management App/force-app/main/default/lwc/icyReferralRecordInfo/icyReferralRecordInfo.html, MAiD - Case Management App/force-app/main/default/lwc/icyReferralRecordInfo/icyReferralRecordInfo.js, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Other_Relationship_Cell__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Other_Relationship_Home__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Other_Relationship_Other__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Preferred_Contact_s_Name_Cell__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Preferred_Contact_s_Name_Home__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Preferred_Contact_s_Name_Other__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Relationship_to_Individual_Cell__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Relationship_to_Individual_Home__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Relationship_to_Individual_Other__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General_Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical_Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/validationRules/Relationship_Type_Other_Cell.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/validationRules/Relationship_Type_Other_Home.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/validationRules/Relationship_Type_Other_Other.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
BCMOHAD-25680 - Note who the preferred method of contact is
Fixes # (BCMOHAD-25680)
=> BCMOHAD-25680 - Note who the preferred method of contact is

MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
BCMOHAD-25702-2 Fix Metadata missing from Git Repo because of Merge PR#873
=> BCMOHAD-25702-2 Fix Metadata missing from Git Repo

MAiD - Case Management App/force-app/main/default/objects/Referral__c/listViews/ICY_All_Admin_PL_Closed_Referrals.listView-meta.xml
BCMOHAD-25699-2 Update List view Sharing
Fixes # (BCMOHAD-25699)
POST DEPLOYMENT STEPS TO BE DONE IN UAT/PROD(ALREADY DONE IN QA)
To Update historical Data for Field Team_members_Id__c on Referral Object follow below steps:
if ticket BCMOHAD-25700 has been already deployed to UAT/PROD Comment out all reference to : ICY_CaseMember_Controller.updateCaseTeamSize in trigger Case_Member.trigger ( 2 occurences)
deactivate all active validation Rule on Referral
Run below Query to get the Extract the Data needed:
select Id,ICY_Status__C from case_member__C where ICY_Status__c='Active'
Run Data Import/update on same file extracted above
Remove the commented lines in step 1 (for ICY_CaseMember_Controller.updateCaseTeamSize) in Trigger Case_Member.trigger
Activate back validation Rule
7)Add below …
=> BCMOHAD-25699-2 Update List view Sharing

MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js, MAiD - Case Management App/force-app/main/default/lwc/icyReferralRecordInfo/icyReferralRecordInfo.html
BCMOHAD-25681 - Adding Current School to referrals
Fixes # (BCMOHAD-25681)
=> BCMOHAD-25681 - Adding Current School to referrals

MAiD - Case Management App/force-app/main/default/objects/Intake__c/fields/ICY_Intake_Close_Date__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/fields/ICY_Rationale__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Referral_Close_Reason__c.field-meta.xml
BCMOHAD-26366 - Set history Tracking
Fixes # (BCMOHAD-26366)
=> BCMOHAD-26366 - Set history Tracking

MAiD - Case Management App/force-app/main/default/objects/Case_Member__c/fields/Report_User_Role__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/reportTypes/MMHA_Reporting_Report_Type.reportType-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYSharedIndicatorsReports/Copy_of_ICY_being_seen_1_Members_b51.report-meta.xml
Bcmohad 25700 1 Update Report
Fixes # (Bcmohad 25700)
POST DEPLOYMENT STEPS TO RUN IN UAT,PROD ( QA ALREADY DONE)
================================================
To Update historical Data for Field  Case_Team_Size__c  on Case Object follow below steps:
1)  if  ticket BCMOHAD-25699 has been already deployed to UAT/PROD Comment out all reference to : ICY_CaseMember_Controller.updateReferralTeamMemberIds  in trigger Case_Member.trigger ( 2 occurences : Line 16 ,line 29)
2)  Run below Query to get the Extract the Data needed:
Select Id,ICY_Status__C from case_member__C where ICY_Case__c <> null 
3) Run Data Import/update on same file extracted above 
4) Remove the commented lines in step 1 (Line 16 ,line 29) in Trigger Case_Member.trigger
=> Bcmohad 25700 1 Update Report

MAiD - Case Management App/force-app/main/default/flexipages/ICY_Intake_Record_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/flexipages/ICY_Referral_Record_Page.flexipage-meta.xml
BCMOHAD-26379 - Adding History Tab
Fixes # (BCMOHAD-26379)
=> BCMOHAD-26379 - Adding History Tab

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Error Log.layout-meta.xml
Updated the Case Error Log Page layout by removing the field
MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Error Log.layout-meta.xml
=> BCMOHAD-26486 || Updated the Page layout

MAiD - Case Management App/force-app/main/default/flows/ICY_Referral_Assign_To_Handler.flow-meta.xml
**1) Row cause check condition is removed. Now the flow removes existing Referral sharing records created by all types of (Row Cause) before Re-assigning the referral and then created a new referral share records without any blocker.**
=> BCMOHAD-26340

MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js, MAiD - Case Management App/force-app/main/default/objects/Referral__c/validationRules/Referral_Source_Descirption_Other.validationRule-meta.xml
BCMOHAD-26365 - Make Referral Source Description Mandatory if other
Fixes # (BCMOHAD-26365)
=> BCMOHAD-26365 - Make Referral Source Description Mandatory if other

MAiD - Case Management App/force-app/main/default/dashboards/ICYSharedIndicatorsDashboard/HmaHZUxiushsYZNnKSDrLjsAEZWPjZ.dashboard-meta.xml, MAiD - Case Management App/force-app/main/default/reports/ICYSharedIndicatorsReports/Copy_of_ICY_being_seen_1_Members_b51.report-meta.xml
BCMOHAD-25700-2 - Update Dashboard and Report
Fixes # (BCMOHAD-25700)
POST DEPLOYMENT STEPS TO RUN IN UAT,PROD ( QA ALREADY DONE)
================================================
To Update historical Data for Field  Case_Team_Size__c  on Case Object follow below steps:
1)  if  ticket [BCMOHAD-25699](https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-25699) has been already deployed to UAT/PROD Comment out all reference to : ICY_CaseMember_Controller.updateReferralTeamMemberIds  in trigger Case_Member.trigger ( 2 occurences : Line 16 ,line 29)
2)  Run below Query to get the Extract the Data needed:
Select Id,ICY_Status_C from case_member__c  where ICY_Case_c <> null 
3) Run Data Import/update on same file extracted above 
4) Remove the commented lines in step 1 (Line 16 ,line 29) in …
=> BCMOHAD-25700-2 - Update Dashboard and Report

MAiD - Case Management App/force-app/main/default/classes/ICY_CaseMember_Controller.cls
BCMOHAD-25700-3 - Update Controller
Fixes # (BCMOHAD-25700)
POST DEPLOYMENT STEPS TO RUN IN UAT,PROD ( QA ALREADY DONE)
=============================================================================
To Update historical Data for Field Case_Team_Size__c on Case Object follow below steps:
1) if ticket [BCMOHAD-25699](https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-25699) has been already deployed to UAT/PROD Comment out all reference to : ICY_CaseMember_Controller.updateReferralTeamMemberIds in trigger Case_Member.trigger ( 2 occurences : Line 16 ,line 29)
2)  Run below Query to get the Extract the Data needed:
Select Id,ICY_Status_C from case_member__c where ICY_Case_c <> null
4) Run Data Import/update on same file extracted above
5) Remove the commented lines in step 1 (Line 16 ,line …
=> BCMOHAD-25700-3 - Update Controller

MAiD - Case Management App/force-app/main/default/classes/ICY_CaseMember_Controller.cls, MAiD - Case Management App/force-app/main/default/flows/ICY_Referral_Assign_To_Handler.flow-meta.xml
=> BCMOHAD-25700 || UAT Bug fix 

MAiD - Case Management App/force-app/main/default/lwc/icyContactsComponent/icyContactsComponent.html
BCMOHAD-25703- Update LWC
Fixes # (BCMOHAD-25703)
- [X ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or that my feature works
=> BCMOHAD-25703- Update LWC

MAiD - Case Management App/force-app/main/default/classes/ICY_Notes_Documents_Controller.cls, MAiD - Case Management App/force-app/main/default/lwc/iCY_NotesComponent/iCY_NotesComponent.html, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.html, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.js, MAiD - Case Management App/force-app/main/default/objects/ICY_Notes__c/fields/ICY_Meeting_Date__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
Bcmohad 25682 - Add meeting Date 
Fixes # (Bcmohad 25682)
=> Bcmohad 25682 - Add meeting Date 

MAiD - Case Management App/force-app/main/default/lwc/icyContactsComponent/icyContactsComponent.html, MAiD - Case Management App/force-app/main/default/lwc/icyContactsComponent/icyContactsComponent.js
BCMOHAD-25703-1 - Updating LWC
Fixes # (BCMOHAD-25703)
=> BCMOHAD-25703-1 - Updating LWC

MAiD - Case Management App/force-app/main/default/classes/ICY_Notes_Documents_Controller.cls, MAiD - Case Management App/force-app/main/default/lwc/iCY_NotesComponent/iCY_NotesComponent.html, MAiD - Case Management App/force-app/main/default/lwc/iCY_NotesComponent/iCY_NotesComponent.js, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditDocument/icyCreateEditDocument.html, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditDocument/icyCreateEditDocument.js, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.html, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.js, MAiD - Case Management App/force-app/main/default/lwc/icyDocumentsComponent/icyDocumentsComponent.html, MAiD - Case Management App/force-app/main/default/lwc/icyDocumentsComponent/icyDocumentsComponent.js
BCMOHAD-25701 ICY - Enable editing note and document type (collaborative/restricted)
Fixes # (BCMOHAD-25701)
=> BCMOHAD-25701 ICY - Enable editing note and document type (collaborative/restricted)

MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.html
BCMOHAD-25701-1 - Update LWC for meeting date
Fixes # (BCMOHAD-25701)
=> BCMOHAD-25701-1 - Update LWC for meeting date

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/REQ_Q25__c.field-meta.xml
Updated the formula field **REQ_Q25** which was not working properly
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/REQ_Q25__c.field-meta.xml
=> BCMOHAD-26593 || Updated the formula for Req_q25

MAiD - Case Management App/dev-app-post/main/default/customMetadata/IDP_User_Registration_User_Mapping.ICY_Peace_River_South_Team_PL.md-meta.xml
Salesforce User role corrected for Peace river south region.
Fixes # BCMOHAD-26507
https://github.com/bcgov/MOH-MAiD/pull/899
=> BCMOHAD-26507 Salesforce User role corrected for Peace River South Region.

MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml
Updated the flow which was not working as intended
MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml
=> BCMOHAD-27290 || Updated the flow

MAiD - Case Management App/force-app/main/default/objects/Case_Member__c/Case_Member__c.object-meta.xml
BCMOHAD-27573- Revise name to Team Members
Fixes # (BCMOHAD-27573)
- [X Bug fix (non-breaking change which fixes an issue)
=> BCMOHAD-27573- Revise name to Team Members

MAiD - Case Management App/force-app/main/default/objects/Case_Member__c/fields/Referral__c.field-meta.xml
Bcmohad 27573 1 Updating List view name on Referral Field
Fixes # (BCMOHAD-27573)
=> BCMOHAD-27573-1

MAiD - Case Management App/force-app/main/default/lwc/icyReopenIntake/icyReopenIntake.js
BCMOHAD-27575- Remove field update
Fixes # (BCMOHAD-27575)
=> BCMOHAD-27575- Remove field update

MAiD - Case Management App/force-app/main/default/flows/ICY_Referral_Assign_To.flow-meta.xml
BCMOHAD-27574-1-Updating access to flow
Fixes # (BCMOHAD-27574)
=> BCMOHAD-27574-1-Updating access to flow

MAiD - Case Management App/force-app/main/default/objects/Referral__c/listViews/ICY_All_Closed_Referrals.listView-meta.xml, MAiD - Case Management App/force-app/main/default/sharingRules/Referral__c.sharingRules-meta.xml
BCMOHAD-27571-UpdateSharingRules and List views
Fixes # (BCMOHAD-27571)
MANUAL STEP
===========
BACKUP DATA PRIOR DEPLOYMENT
=> BCMOHAD-27571-UpdateSharingRules and Listviews

MAiD - Case Management App/.forceignore, MAiD - Case Management App/manifest/package.xml, MAiD - Case Management App/sfdx-project.json
Updated the Packsge.xml with the report names
Updated the .forceignore page to remove most of the warnings
Updated sfdx-project.json file Api version to 61.0
=> BCMOHAD-26859 || Updated the reports in the package.xml

MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js
BCMOHAD-27393-1-Removing Error msg
Fixes # (BCMOHAD-27393)
=> BCMOHAD-27393-1-Removing Error msg

MAiD - Case Management App/force-app/main/default/classes/ICY_BatchToSendInactiveCaseNotesTest.cls, MAiD - Case Management App/force-app/main/default/classes/ICY_Notes_Documents_Controller.cls, MAiD - Case Management App/force-app/main/default/classes/ytsCaseTriggerHandlerTest.cls, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.html, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.js, MAiD - Case Management App/force-app/main/default/objects/ICY_Notes__c/fields/Mode_Location__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/ICY_Notes__c/fields/Other_Mode_Location__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
Bcmohad 27969 ICY Enhancements - #6 Add more case note “Mode Location” drop-down options
Fixes # (Bcmohad 27969)
=> Bcmohad 27969 ICY Enhancements - #6 Add more case note “Mode Location” drop-down options

MAiD - Case Management App/force-app/main/default/workflows/Referral__c.workflow-meta.xml
BCMOHAD-28066-UpdateEmailAlertFrom
Fixes # (BCMOHAD-28066-)
=> BCMOHAD-28066-UpdateEmailAlertFrom

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Flagged_Case__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Flagged_Case_field_edit_access.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
Created New field **Flagged Case**, added it to the **MAiD Case pagelayout**.
Provided the access to **Analyst** and **Manager** through **permission sets**.
Created a new **Validation Rule** to prevent the editing of the field **Flagged Case** in the record.
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Flagged_Case__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Flagged_Case_field_edit_access.validationRule-meta.xml
MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset- …
=> BCMOHAD-28013 || Created New Field "Flagged Case"

MAiD - Case Management App/force-app/main/default/flows/Update_Related_Case_Record.flow-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Education_History__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
=> BCMOHAD 28035

MAiD - Case Management App/force-app/main/default/sharingRules/Case.sharingRules-meta.xml
=> BCMOHAD 28017

MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/validationRules/Assessment_date_check.validationRule-meta.xml
=> BCMOHAD-28042_v1 || 1633 Assessment Date Validation Rule

MAiD - Case Management App/.sf/config.json, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q05__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q20__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q10__c.field-meta.xml
=> BCMOHAD-28018-28020-28031 || Formula update

MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Flagged_Case_field_edit_access.validationRule-meta.xml
Updated the formula, Description and error message of the validation rule: Flagged_Case_field_edit_access
MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Flagged_Case_field_edit_access.validationRule-meta.xml
=> BCMOHAD-28013-V1 || Updated the formula, Description and error message

MAiD - Case Management App/force-app/main/default/flows/Update_Related_Case_Record.flow-meta.xml
=> BCMOHAD-28035 v1 || Flow fix

MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reason_for_Flagging__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Reason_for_Flagging_cannot_be_null.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Reason_for_Flagging_case_Edit.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
Created a new field "Reason_for_Flagging__c", Added it to the MAiD-Case Layout
Given the edit permissions through permission sets
Added validation rules to restrict editing of the field once the record is created.
MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reason_for_Flagging__c.field-meta.xml
MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Reason_for_Flagging_cannot_be_null.validationRule-meta.xml
MAiD - Case Management …
=> BCMOHAD-28015 && BCMOHAD-28016 || Created New fields and Validation Rules

MAiD - Case Management App/force-app/main/default/flexipages/Practitioner_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/fields/Case_Owner__c.field-meta.xml
=> BCMAHAD-28038 || Formula fix and flexipage fix.

MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Reason_for_Flagging_case_Edit.validationRule-meta.xml
I have updated the error message from **Flagged case** to **Reason for Flagging case**
MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Reason_for_Flagging_case_Edit.validationRule-meta.xml
=> BCMOHAD-28015-V1 || Updated the error message

MAiD - Case Management App/force-app/main/default/reports/ICYReportsPL/Cases_with_no_case_notes_in_last_30_days_t9c.report-meta.xml
BCMOHAD-28099-1 updating Report
Fixes # (BCMOHAD-28099-1)
=> BCMOHAD-28099-1 updating Report

MAiD - Case Management App/force-app/main/default/classes/ICY_Notes_Documents_Controller.cls, MAiD - Case Management App/force-app/main/default/lwc/iCY_NotesComponent/iCY_NotesComponent.html, MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.js
Bcmohad 27969 1 update LWC 
Fixes # (Bcmohad 27969)
=> Bcmohad 27969 1

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ADM_Q25__c.field-meta.xml
Updated the formula field and changed the Data Type from Number to Text
MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ADM_Q25__c.field-meta.xml
=> BCMOHAD-28034 || Updated the formula

MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
=> BCMOHAD 28036 v1 || MAiD Analyst Permission set update

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q10__c.field-meta.xml
=> BCMOHAD-28369 RES_Q10 formula changes

MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q05__c.field-meta.xml
=> BCMOHAD-28367 DIS_Q05 Formula Changes

MAiD - Case Management App/force-app/main/default/classes/DeleteAssessmentofEligibilityBatchTest.cls, MAiD - Case Management App/force-app/main/default/classes/DeleteAssessmentofEligibilityBatchTest.cls-meta.xml, MAiD - Case Management App/force-app/main/default/classes/DeleteAssessmentofEligibilityCasesBatch.cls, MAiD - Case Management App/force-app/main/default/classes/DeleteAssessmentofEligibilityCasesBatch.cls-meta.xml
Created a Batch class to run everyday at 1 am to delete the **MAiD Assesment of Eligibility** cases which has **Case_Type_Reported_Date__c more than 60days** and the **Status** is in **"Awaiting Forms"**
**One-Time Post-Deployment Step:**
Open Developer Console, In the Debug select Open Execute Anonymous Window
Paste the following code and Execute it:
**String cronExp = '0 0 1 * * ?';
System.schedule('DeleteAssessmentofEligibilityCasesBatch', cronExp, new DeleteAssessmentofEligibilityCasesBatch());**
To confirm the execution In Setup, search for Scheduled Jobs, once we are in Scheluded Jobs we can see **DeleteAssessmentofEligibilityCasesBatch** Activated.
MAiD - Case Management App/force-app/main/default/classes/DeleteAssessmentofEligibilityCasesBatch.cls
MAiD - Case Management …
=> BCMOHAD-28237 || Created new Apex class

MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html, MAiD - Case Management App/force-app/main/default/objects/Account/fields/Pronouns__c.field-meta.xml
Updated the Pronouns length to 100 and added the max length condition 
MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html
MAiD - Case Management App/force-app/main/default/objects/Account/fields/Pronouns__c.field-meta.xml
=> BCMOHAD-28752 || Updated the length

MAiD - Case Management App/force-app/main/default/reports/ICYReports/Case_with_Case_Members_Report_8QF.report-meta.xml
BCMOHAM-24473- Remove Case member name
Fixes # (BCMOHAM-24473)
=> BCMOHAM-24473- Remove Case member name

MAiD - Case Management App/force-app/main/default/flexipages/ICY_Intake_Record_Page.flexipage-meta.xml, MAiD - Case Management App/force-app/main/default/flexipages/ICY_Referral_Record_Page.flexipage-meta.xml
BCMOHAD-28573-1-Add Delete button
Fixes # (BCMOHAD-28573-)
=> BCMOHAD-28573-1-Add Delete button

MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY General Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Close Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-ICY Medical Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Referral__c-Read-Only.layout-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.html, MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js, MAiD - Case Management App/force-app/main/default/lwc/icyReferralRecordInfo/icyReferralRecordInfo.html, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Can_We_Leave_a_Message_On_Email__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Preferred_Method_of_Contact__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Individual_Email_Address__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Other_Relationship_Email__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Preferred_Contact_s_Name_Email__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/Relationship_to_Individual_Email__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General_Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical_Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/Read_Only.recordType-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Referral__c/validationRules/Relationship_Type_Other_Email.validationRule-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Support_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/Salesforce_Backup_Administrator.permissionset-meta.xml
=> BCMOHAD-29583- Adding email as a new communication channel to the contact details.

MAiD - Case Management App/force-app/main/default/flows/Sync_Case_ConsenttoEvaluation_to_RelatedIntakes.flow-meta.xml, MAiD - Case Management App/force-app/main/default/flows/Sync_Intake_ConsenttoEvaluation_to_RelatedCase.flow-meta.xml, MAiD - Case Management App/force-app/main/default/labels/CustomLabels.labels-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Case-ICY_Close_layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Case-ICY_Standard.layout-meta.xml, MAiD - Case Management App/force-app/main/default/layouts/Intake__c-ICY Intake Layout.layout-meta.xml, MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.html, MAiD - Case Management App/force-app/main/default/lwc/icyCompleteIntakeLWC/icyCompleteIntakeLWC.js, MAiD - Case Management App/force-app/main/default/objects/Case/fields/Consent_to_Evaluation__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/objects/Intake__c/fields/Consent_to_Evaluation__c.field-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml, MAiD - Case Management App/force-app/main/default/permissionsets/Salesforce_Backup_Administrator.permissionset-meta.xml
ConsentTo evaluation functionality added.
**Enhancement Number : 5A**
https://github.com/bcgov/MOH-MAiD/pull/955
=> BCMOHAD-29584 ConsentToEvaluation Functionality-Enhancement Number : 5A

MAiD - Case Management App/force-app/main/default/lwc/icyReferralRecordInfo/icyReferralRecordInfo.html, MAiD - Case Management App/force-app/main/default/reportTypes/ICY_Open_Cases_With_ConsentToEvaluation.reportType-meta.xml, MAiD - Case Management App/manifest/package.xml
Missing UI alignment change on the referral detail page is added.
=> BCMOHAD-29586 V1 UI Changes

MAiD - Case Management App/force-app/main/default/lwc/icyNewReferral/icyNewReferral.js
BCMOHAD-30092-Adding Warning message when a referral is created outside the assigned region
Fixes # (BCMOHAD-30092)
=> BCMOHAD-30092-Adding Warning message
